### ISSUE TITLE
Coercing NSNull value to nil in shouldSetValue:atKeyPath: -- should be fixed.

### ISSUE THREAD

**Issue by dmishe** [RestKit/RestKit#1043]
I get this log message when mapping JSON payload such as:

```
{
    'image': null
}
```

In CoreData the image property is defined as Transformable.

**Comment by wangpingsx** [comment]
I use swift and restkit and my solution is make null properties to NSObject instead of string ...

http://baiduhix.blogspot.co.uk/2015/03/restkit-swift-handle-null-value.html
