### ISSUE TITLE
POST object without a request descriptor fails to send params

### ISSUE THREAD

**Issue by brendensoares** [RestKit/RestKit#1123]
I've spent a couple hours reviewing docs and code and can't figure out what's wrong. I can do GET requests fine with the object mappings I have.

Here's my condensed debugging code:

```
RKObjectMapping *surveyMapping = [RKObjectMapping mappingForClass:[Survey class]];
[surveyMapping addAttributeMappingsFromDictionary:@{@"surveyName" : @"name" }];

RKResponseDescriptor *surveyResponseDescriptor = [RKResponseDescriptor responseDescriptorWithMapping:surveyMapping pathPattern:@"surveyInstance?key=fa095738-ebeb-4383-bfde-a331b7dcb391" keyPath:nil statusCodes:[NSIndexSet indexSetWithIndex:200]];
[self.apiManager addResponseDescriptor:surveyResponseDescriptor];
[self.apiManager.router.routeSet addRoute:[RKRoute routeWithClass:[Survey class] pathPattern:@"surveyInstance" method:RKRequestMethodPOST]];

Survey *survey = [Survey alloc];
[survey setName: @"TEST TEST TEST"];
// POST new survey to API
[[APP_DELEGATE apiManager] postObject:survey path:@"surveyInstance?key=fa095738-ebeb-4383-bfde-a331b7dcb391" parameters:@{@"TEST":@"TEST VALUE"} success:^(RKObjectRequestOperation *operation, RKMappingResult *mappingResult) {
    // Success
} failure:^(RKObjectRequestOperation *operation, NSError *error) {
    // Failure
}];
```

My intercepted HTTP POST:

```
POST http://api.test.xxx.com/v1/surveyInstance?key=fa095738-ebeb-4383-bfde-a331b7dcb391 HTTP/1.1
Host: api.test.xxx.com
Proxy-Connection: keep-alive
Accept: application/json
Content-Length: 0
Connection: keep-alive
Accept-Language: en, fr, de, ja, nl, it, es, pt, pt-PT, da, fi, nb, sv, ko, zh-Hans, zh-Hant, ru, pl, tr, uk, ar, hr, cs, el, he, ro, sk, th, id, ms, en-GB, ca, hu, vi, en-us;q=0.8
User-Agent: AppName/699 (iPad Simulator; iOS 6.0; Scale/1.00)

TEST=TEST%20VALUE
```

I'm using version 0.20. Thanks for your time.

**EDIT: added "TEST" parameter to request. It's clearly making a successful request, but not mapping the NSObject aka Survey's attributes.**

**Comment by tricpony** [comment]
I have a related issue, may actually be identical, but nothing in this thread helps.  I want to use rest kit to send up a payload without using any of the bells & whistles, no mappings no descriptors.  I will assemble the payload myself, set all the header values and using the objectManager putObject:<nil>path:<endPoint>parameters:<payload>success:failure:  -- problem is I can not get this to work.  Any help would be great -- here's the error I get:

{ status code: 200, headers {
    Connection = "keep-alive";
    "Content-Length" = 0;
    "Content-Type" = "text/html; charset=UTF-8";
    Date = "Fri, 03 Feb 2017 04:29:30 GMT";
    Server = "Apache/2.4.25 (Unix) OpenSSL/1.0.1k-fips";
} }, NSLocalizedDescription=Expected content type {(
    "application/x-www-form-urlencoded",
    "application/json"
)}, got text/html}

**Comment by tricpony** [comment]
Actually Restkit will work as outlined above.  My problem was on the server.  Sorry.
