### ISSUE TITLE
Metadata Mapping Does Not Work for Identification Attributes

### ISSUE THREAD

**Issue by blakewatters** [RestKit/RestKit#1202]
Extracted from a comment on #1174:

``` objc
RKEntityMapping *emailPreviewMapping = [RKEntityMapping mappingForEntityForName:@"EmailPreview" inManagedObjectStore:self.managedObjectStore];
[emailPreviewMapping addAttributeMappingsFromDictionary:@{
    @"@metadata.routing.parameters.path" : @"folderPath"
}];
[emailPreviewMapping addAttributeMappingsFromArray:@[ @"subject", @"senderFullname", @"senderEmail", @"messageId"]];
[emailPreviewMapping addConnectionForRelationship:@"folder" connectedBy:@{ @"folderPath" : @"path" }];
emailPreviewMapping.identificationAttributes = @[ @"folderPath", @"messageId" ];
I access EmailPreviews with the following URL pattern: /folder/:path/content/
```

Produces the following exception:

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '[<__NSCFDictionary 0xa256be0> valueForKeyPath:]: this class does not implement the metadata operation.'`

in RKManagedObjectMappingOperationDataSource.m:64

---

After some research, the problem appears to be in RKManagedObjectMappingOperationDataSource.m:239. RKEntityIdentificationAttributesForEntityMappingWithRepresentation does not evaluate metadata mappings.
The entire RKManagedObjectMappingOperationDataSource class does not know about metadata at all.

One possible solution might be to perform metadata mapping before asking the data source for a Core Data reference object.

**Comment by Dianar2013** [comment]
it not work for personnal mapping [emailPreviewMapping addAttributeMappingsFromDictionary:@{
     @"@metadata.mapping.rootKeyPath" : @"folderPath"
}]; as I set    metaData = @{@"page",@(1)} , [emailPreviewMapping addAttributeMappingsFromDictionary:@{
     @"@metadata.mapping.page" : @"page"
}];   then in fact page=NULL or page = 0

**Comment by Dianar2013** [comment]
But I want page = 1
