### ISSUE TITLE
receiving an array of strings and mapping it

### ISSUE THREAD

**Issue by Licenser** [RestKit/RestKit#1290]
I am trying to talk to an API that returns some data in the form:

``` json
["531ec31c-256d-4b47-84ff-dcd07bb2d72d","51091625-dcaa-48d4-ada1-899fd29c6046"]
```

And it seems not possible to map this to anything remotely usable (aside form null). The API reference does not mention this use case and google only turns up questions in regards to this instead of answers.

Is it really a use case that isn't implemented right now or am I missing something very obviouse?

Cheers,
Heinz

**Comment by cimlman** [comment]
Hi,
is the opposite scenario also possible with RestKit? I would like to POST a request its body is a JSON array of strings. I have written a more detailed question at StackOverflow.

http://stackoverflow.com/questions/28369558/posting-json-array-of-strings-with-restkit

Thanks.
