### ISSUE TITLE
Funny behavior with Charles Proxy

### ISSUE THREAD

**Issue by bobspryn** [RestKit/RestKit#1383]
This may not be a RestKit bug, but it's looking that way (or potentially AFNetworking).

I always use Charles Proxy while doing any networking work with iOS simulator. Recently (in the last 2 weeks) it stopped working properly. At first I suspected it was a problem with either the most recent Xcode or Java update, but other non-restkit applications seem to work fine, as do older restkit projects (pre 20.0).

All of the sudden when I make requests, I can see them complete successfully in Charles, but they don't complete in the app. Oddly, if I then quit Charles Proxy before the timeout period hits, the request then completes in the app.

I'm not doing anything the least bit strange with my restkit setup, and didn't change anything recently.

I'm on the development branch, but I see the same behavior on the master branch. Which is extremely strange, because things WERE working properly a couple weeks ago on development.

I've reinstalled Charles, reverted Java to the previous version, checked my system network settings. Since other apps work correctly, including older restkit apps, I'm suspecting that there's something weird with the way RestKit behaves that broke with the most recent Xcode.

**Comment by adityapare** [comment]
I am using registered charles and was working fine but suddenly not working for android and iOS both.
Any specific reason for it can any one help me sort it out
