### ISSUE TITLE
RestKit 0.20.1 does not properly map to NSDecimalNumber

### ISSUE THREAD

**Issue by ghost** [RestKit/RestKit#1405]
Hello,

Our JSON contains 0.7689993, but RestKit incorrectly maps the NSDecimalNumber to 0.7689993000000001.

**Comment by wanxsb** [comment]
`@property (nonatomic, retain) NSNumber * branch_id;
@property (nonatomic, retain) NSNumber * id;
@property (nonatomic, retain) NSDecimalNumber * price;
@property (nonatomic, retain) NSNumber * sale_quantity;
@property (nonatomic, retain) NSNumber * shop_id;
@property (nonatomic, retain) NSNumber * stock_quantity;
@property (nonatomic, retain) NSDecimalNumber * vip_price;
`
I've try to use NSDecimalNumber and the server respond like as follows:
`
       "id": 2261,
        "price": "0.68",
        "vip_price": "0.33",
        "cost_price": "0.1",
        "stock_quantity": 113,
        "sale_quantity": 3,
        "sku": "bde09062-23f5-4032-aa9f-ae9db5613e71",
        "option_values": [],
        "shop_id": 2,
        "branch_id": 25,
        "images": [],
        "avatar": ""
`

However, it still show 0.679999999999

I've also tried the way of importing RKJSONKitSerialization. it still not working.

**Comment by brunic** [comment]
if use @property (nonatomic, retain) NSString * price;, is it OK?

**Comment by arctouch-ericchamberlain** [comment]
If I recall correctly, from two years ago, the problem is that the parsers convert the string to NSNumber, then to NSDecimal number.  You may have to explicitly convert the string directly to a NSDecimalNumber.

**Comment by elviin** [comment]
Sending down decimal numbers within strings is not an option if there are multiple responses in our api with multiple decimals and other clients that can parse these values correctly. Where is the related code in Restkit responsible for the conversion?

For example: 9.30 is parsed to NSDecimalNumber as 9.300000001

Restkit 0.26.0
