### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed

### ISSUE THREAD

**Issue by SureshSc** [RestKit/RestKit#1511]
When i am trying to hit HTTPS Un trusted site with Restkit POST object, i am getting this error. When i google its says NSURLErrorUserCancelledAuthentication. How to handle this

**Comment by masterrr** [comment]
Well, not the 
#define AFNETWORKING_ALLOW_INVALID_SSL_CERTIFICATES 1
but
#define _AFNETWORKING_ALLOW_INVALID_SSL_CERTIFICATES_ 1
worked for me (code is using the one with underscores)
