### ISSUE TITLE
Defining multiple response descriptors results in adding a nil coredata object

### ISSUE THREAD

**Issue by dlia** [RestKit/RestKit#1514]
Hi,

I have defined x response descriptors for a certain server. Creating, updating and removing objects works. I have made my experiment on the RKTwitterCoreData example. I changed some keypaths, pathPatterns but the overall config is the same as in the example. I am using RestKit 0.20.3.

I defined the following descriptors:

```
RKResponseDescriptor *responseDescriptor4:
-> pathPattern:@"/rest/Store/search"
-> keyPath:@"data.models"
                                                                                            RKResponseDescriptor *responseDescriptor5:
-> pathPattern:@"/rest/Store/:storeId"
-> keyPath:@"data"
                                                                                           RKResponseDescriptor *responseDescriptor6:
-> pathPattern:@"/rest/Store"
->  keyPath:@"data"
```

These 3 response descriptors should not effect each other. However when I use all 3 response descriptors at once, RestKit/CoreData will add a nil object when I retrieve all objects from "/rest/Store/search". If I remove responseDescriptor6, then the retrieval of all objects at '/rest/Store/search` is fine and no nil objects are inserted. I always reset the simulator.

I find it strange that responseDescriptor6 influences responseDescriptor4.

I have added some screenshots to demonstrate the possible bug.

PS: The problem could be related to issue #1510.

![restkit bug 02 fails](https://f.cloud.github.com/assets/5071827/840705/9ffefcb2-f37a-11e2-9259-973fa7232f70.jpeg)
![restkit bug 01 ok](https://f.cloud.github.com/assets/5071827/840706/a004bdfa-f37a-11e2-89d0-326c227b7169.jpeg)
![restkit bug 04 ok coredata with debug](https://f.cloud.github.com/assets/5071827/840707/a00664f2-f37a-11e2-8f11-9d609df970c5.jpeg)
![restkit bug 03 fails coredata with debug](https://f.cloud.github.com/assets/5071827/840708/a006c370-f37a-11e2-91b3-ecf1a1cce30c.jpeg)

**Comment by saiday** [comment]
@segiddins You mean request pattern like `/rest/Store/search` that gets two response descriptors matched will get double mapping results in anyway? 

Is there's anyway to prevent it?
