### ISSUE TITLE
Add support for multiple path-patterns in RKResponseDescriptor

### ISSUE THREAD

**Issue by benlime** [RestKit/RestKit#1524]
As the title says, it would be handy to have the possibility to provide an NSArray to the path-patterns of responseDescriptorWithMapping:mapping:pathPattern:keyPath:statusCodes. This would eliminate the need of creating multiple RKResponseDescriptor objects if you have multiple path-patterns for the same mapping.

**Comment by saiday** [comment]
Is this requirements been supported? Didn't see discussions about this topic.

**Comment by segiddins** [comment]
Just use multiple descriptors.
