### ISSUE TITLE
Custom mapping of CLLocation property

### ISSUE THREAD

**Issue by gabro** [RestKit/RestKit#1555]
Hi,
this is my object interface

```
@interface SSClip : NSManagedObject
...
@property (nonatomic, retain) CLLocation * location;
...
@end
```

`location` is a transformable property on CoreData.

Any chance I can map this JSON to CLLocation and vice-versa?

```
{
    "clip" : {
        ...
        "location" : {
            "latitude" : 12345,
            "longitude": 12345
        }
        ...
    }
}
```

I found a related issue (https://github.com/RestKit/RestKit/issues/434https://github.com/RestKit/RestKit/issues/434), but I'm not satisfied with the proposed solution.

I'd prefer using a `CLLocation` object directly, so is there a way to perform a custom JSON mapping?

**Comment by kpavankotesh** [comment]
@blakewatters Any swift implementation for this? I am trying to implement as below.

```swift
func transformValue(_ inputValue: Any?, toValue outputValue: Any?, of outputValueClass: AnyClass) throws -> Bool {
    var outputValue = outputValue
    
    if outputValueClass is String.Type {
      outputValue = (inputValue as? String)?.uppercased()
    }
    
    return true
  }
```

When I do this, I get this error `RKValueTransformer subclasses must provide a concrete implementation of 'transformValue:toValue:ofClass:error:'`

**Comment by kpavankotesh** [comment]
@Kurry Any help on this will be appreciated.
