### ISSUE TITLE
NSNumber -> NSDate unix timestamp in milliseconds

### ISSUE THREAD

**Issue by gabro** [RestKit/RestKit#1587]
I receive from a webserver a unix timestamp in milliseconds as a number (represented as a `NSNumber`), for instance

```
1377993600000 // -> Sun, 01 Sep 2013 00:00:00 GMT
```

RestKit converts it to a `intValue` and uses it assuming the value contains seconds, producing the following - wrong - `NSDate`

```
1948-02-09 10:46:24 +0000
```

I need to customize this transformation and convert the timestamp to seconds, but while I know I can provide a custom formatter for the `NSString` -> `NSDate` conversion, how can I customize the `NSNumber` -> `NSDate` transformation?

**Comment by elviin** [comment]
A similar issue is with query params, the NSDate parameters are printed in the string format, not as a number in milliseconds:

`- (NSString *)URLEncodedStringValueWithEncoding:(NSStringEncoding)stringEncoding {
          
    if (!self.value || [self.value isEqual:[NSNull null]]) {
        return TSNAFRKPercentEscapedQueryStringKeyFromStringWithEncoding([self.field description], stringEncoding);
    } else if (self.value && ([NSStringFromClass([self.value class]) isEqualToString:@"__NSTaggedDate"] ||
                              [NSStringFromClass([self.value class]) isEqualToString:@"NSDate"] ||
                              [NSStringFromClass([self.value class]) isEqualToString:@"__NSDate"])) {
        return [NSString stringWithFormat:@"%@=%@", TSNAFRKPercentEscapedQueryStringKeyFromStringWithEncoding([self.field description], stringEncoding), @(((NSInteger)[self.value timeIntervalSince1970] * TSNNumberOfMillisecondsInOneSecond))];
    }
    else {
        return [NSString stringWithFormat:@"%@=%@", TSNAFRKPercentEscapedQueryStringKeyFromStringWithEncoding([self.field description], stringEncoding), TSNAFRKPercentEscapedQueryStringValueFromStringWithEncoding([self.value description], stringEncoding)];
    }
}`
