### ISSUE TITLE
pod 'RestKit/Testing' will not compile with Restkit 0.21.0

### ISSUE THREAD

**Issue by eladleb** [RestKit/RestKit#1661]
When using the following pod file (not constrained to versions):
pod 'RestKit'
pod 'RestKit/Testing' 

On RKTestFactory.m line 31:
# import "RKManagedObjectStore+RKSearchAdditions.h"

The above is not found and can not compile.

![screen shot 2013-11-05 at 6 57 05 pm](https://f.cloud.github.com/assets/1809338/1475404/5a28860e-463b-11e3-9859-16fa92426184.png)

**Comment by lukecharman** [comment]
It hasn't been, as of 2016.
