### ISSUE TITLE
Can't install last version 'RKObjectManager.h' file not found

### ISSUE THREAD

**Issue by onishinji** [RestKit/RestKit#1681]
Hello, i am upgrading my project using RestKit and now when i compil i have this error:

/Pods/Headers/RestKit/ObjectMapping.h:21:9: 'RKObjectManager.h' file not found

I never touch to the pod project :/

**Comment by ewhite-dev** [comment]
Did you ever figure this out, I am experiencing this now

Xcode 7, updated cocoapods, and then this happens

**Comment by ewhite-dev** [comment]
I'm getting this now, after updating to the 0.39.0 beta 4, still pointing at RestKit 0.22.0

This is only related to my share extension target, but ultimately I can't compile my project at all, so there may be other issues after I solve this one.

**Comment by anton-matosov** [comment]
I have updated to 0.39.0 today and start getting the same issue.
RestKit is the only failing pod

**Comment by segiddins** [comment]
Yes, this is a known is that there's an open PR for.

**Comment by anton-matosov** [comment]
So for you would recommend to stay on 0.38.2?

**Comment by segiddins** [comment]
Or point to my branch, up to you

**Comment by anton-matosov** [comment]
can you give me the branch name?

**Comment by segiddins** [comment]
GitHub should say what branch it's coming from on the PR

**Comment by anton-matosov** [comment]
Can you please point me to the PR as I can't find it either?

**Comment by anton-matosov** [comment]
BTW do you have any idea when this change will be released to the public?

**Comment by ewhite-dev** [comment]
@anton-matosov you can point cocoapods at specific repositories and forks

**Comment by segiddins** [comment]
No idea. It's dependent on a cocoapods PR being finished, and restkit is far from my top priority at the moment.

**Comment by anton-matosov** [comment]
so this is PR against cocoapods repo, not RestKit one. Thanks for your help everyone.
