### ISSUE TITLE
[0.21.0] Milliseconds disappear

### ISSUE THREAD

**Issue by koloritcm** [RestKit/RestKit#1683]
I have searched all over for a solution for this, and I'm really surprised that it can be this hard to just support milliseconds.

My server returns the following date format: `2013-11-23T010:12:56.512Z`

But I have now realized that the milliseconds disappear and never gets stored in in the database (CoreData). I guess this must be a bug as the time is in a correct ISO8601 format and the milliseconds are ignored.

How do you fix this for (1) response transformation and (2) request transformation?

I've tried:

``` objc
NSDateFormatter *iso8601DateFormatter;

iso8601DateFormatter = [NSDateFormatter new];
iso8601DateFormatter.locale = [[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"];
iso8601DateFormatter.timeZone = [NSTimeZone timeZoneWithName:@"UTC"];
iso8601DateFormatter.dateFormat = @"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'";

[[RKValueTransformer defaultValueTransformer] insertValueTransformer:iso8601Formatter atIndex:0];
```

without any success.

**Comment by deberle** [comment]
Same problem here. I ended up commenting out the `+ (void)initialize` code. Is there any reason one shouldn't do this?

**Comment by msqr** [comment]
If you can't (or don't want to) modify the RestKit source, you can work around the `+ (void)initialize` issue like this:

```objc
[RKObjectMapping class]; // make that +initialize method go
NSArray<id<RKValueTransforming>> *xforms = [[RKValueTransformer defaultValueTransformer] valueTransformersForTransformingFromClass:[NSString class] toClass:[NSDate class]];
for ( id<RKValueTransforming> xform in xforms ) {
  if ( [xform isKindOfClass:[RKISO8601DateFormatter class]] ) {
    [[RKValueTransformer defaultValueTransformer] removeValueTransformer:xform];
  }
}
```
