### ISSUE TITLE
InverseMapping on a Model with an NSDate results in exception

### ISSUE THREAD

**Issue by mshawCS** [RestKit/RestKit#1705]
using RestKit 0.21.0
Mapping to an NSDate from our webservice works great. When trying to do an inverse mapping on that same object we get the following:

D restkit.object_mapping:RKMappingOperation.m:920 Finished mapping operation successfully...

Followed by:
 **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (__NSDate)'

Expected result was that the NSDate converted to the proper string representation before passing to NSJSONSerialization. 

Viewing the dictionary object in RKNSJSonSerialization we can see @createdAt": 2013-12-05 20:14:26 PST

**Comment by mshawCS** [comment]
Still looks like this is an issue in the latest RestKit for Cocoapods. Anyone find a solution?

**Comment by segiddins** [comment]
Feel free to submit a PR, @mshawCS!

**Comment by mshawCS** [comment]
Wow that was a quick response @segiddins . Are you talking about a pull request on my own fork?

**Comment by segiddins** [comment]
No, I'd like to see a PR into RestKit I can merge to fix the issue :)

**Comment by mshawCS** [comment]
Oh ok, I thought you were saying you have a fix for it. I'll have another look at it.

**Comment by robertturrall** [comment]
Is this still open? I ask because I have the exact same error when trying a postObject with an inverseMapping including an NSDate. I'm using the latest cocoapods version
