### ISSUE TITLE
Parent object modification attribute prevents nested object mapping

### ISSUE THREAD

**Issue by matej** [RestKit/RestKit#1716]
The current implementation of `RKMappingOperation` consults a data source method called [`mappingOperationShouldSkipPropertyMapping:`](https://github.com/RestKit/RestKit/blob/development/Code/ObjectMapping/RKMappingOperation.m#L892) before proceeding with the actual mapping. `RKManagedObjectMappingOperationDataSource` implements this method and uses the `modificationAttribute` defined in the relevant `RKEntityMaping` to determine if mapping should proceed. 

The problem I'm seeing is that **if `mappingOperationShouldSkipPropertyMapping:` returns YES on the root object, RestKit also skips mapping on all nested objects, although they might have changes themselves**. Our root object's modification dates normally don't get updated when a related object (which happens to be nested in the JSON response) changes.

I think tat a more reasonable assumption / default behavior here would be to recursively continue mapping into nested objects, which would in turn be able to consult their modificationAttribute to determine whether mapping should be performed on them or not.

**Comment by adly-holler** [comment]
+1 For this, big time. @segiddins Your previous rationale that `modificationAttributes` should encompass changes to nested objects doesn't apply anymore, since `modificationAttributes` has been superseded by `modificationAttribute`.

**Comment by segiddins** [comment]
¯\_(ツ)_/¯ I can't really remember this any more...
