### ISSUE TITLE
Lean in and help to get AFNetworking 2.0 support finished. 

### ISSUE THREAD

**Issue by SAJK111** [RestKit/RestKit#2028]
Hi
I know this question has been asked a dozen of times, when the AFNetworking 2.0 support for RestKit is finished. What if we all tried to lean in and help to get this job done? What is the remaining things that need to be done inorder to have a full functional RestKit with AFnetworking 2.0? Are we far from  goal in current experimental branch? What thoughts and ideas need to be thought through? 

I think it could be nice if we all tried to collaborate to make this beautiful library more up to date. 
What are you thoughts? 
- If this is inapproriate, feel free to close this issue.

**Comment by puttin** [comment]
Any news about migrate to `NSURLSession` and drop AFN entirely?

**Comment by ptclarke** [comment]
@puttin There has been some progress but everyone keeps running out of time. Any contributions are welcome. See https://github.com/oligriffiths/RestKit.git

**Comment by faigym** [comment]
Is there any way I can help out? I'm new to nsurlsession.

Thanks!

Faigy

On Sun, Jun 14, 2015 at 6:51 PM, ptclarke <notifications@github.com> wrote:

> @puttin <https://github.com/puttin> There has been some progress but
> everyone keeps running out of time. Any contributions are welcome. See
> https://github.com/oligriffiths/RestKit.git
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RestKit/RestKit/issues/2028#issuecomment-111882147>.
>



-- 

*Faigy Mayer*

faigy.mayer@gmail.com

**Comment by tinora** [comment]
@ptclarke Is the effort on your branch aiming at replacing AFN altogether in favor of NSURLSession or are you trying to update RestKit to AFN 2.x? In case you're (as @blakewatters suggests) trying to go the NSURLSession route and drop AFN:
- How far have you gone already? 
- How much effort is still ahead (approx.)?
- What would you think are to biggest hurdles to take?
- How could I contribute to your work - without promising too much yet - (I have many years of iOS development experience and even more years of development experience in large scale software projects)?

**Comment by tinora** [comment]
@blakewatters First of all a big thanks to you (and the many other contributors) for all you've done to RestKit in last couple of years. It is a fantastic, very well documented framework. I have used it in several Apps and it has saved me a lot of work so far. 
You as THE EXPERT on RestKit what would you think:
- How much effort (approx.) would it be to drop AFN in favor of NSURLSession?
- Is there a preferred way to get started in case I would decide to invest into this effort?
- How big are the chances to get a corresponding branch merged back into the master in a reasonable time frame once it would be ready?

Regards
Tino

**Comment by ptclarke** [comment]
@tinora The approach is to replace AFN with NSURLSessions. Ollie Griffiths has made good progress with this see: https://github.com/oligriffiths/RestKit.git (bear in mind the branch name is now perhaps a misnomer). Remaining effort in the order of weeks but elapsed time will be longer. Approach and coding are in good hands, I think I have a reasonable handle on test cases but wider testing, documentation updates, upgrade path, review by Restkit team and merge into head...

**Comment by segiddins** [comment]
@tinora such a branch would be gladly merged, as long as it had corresponding test coverage and documentation, as is seen throughout all of the RestKit codebase.

**Comment by williamnoto** [comment]
Is it possible for someone to organize a call and organize and dole out the work. I have used restkit throughout heynay and I would like to contribute to keeping it current.

There must be quite a few others like me. Maybe would be good to ask Ray Wenderlich to help corral folks, might actually make a good how to article: "how to organize an open source project."

His restkit tut introduced me to restkit.

**Comment by segiddins** [comment]
@williamnoto the best place to do that is for someone to open up a PR here on GitHub, which hasn't happened yet.

**Comment by williamnoto** [comment]
PR === ??

**Comment by ptclarke** [comment]
@segiddins OK as Ollie has made the biggest steps I will ask him if he is ready to raise a PR

**Comment by segiddins** [comment]
PR == pull request

**Comment by ptclarke** [comment]
@williamnoto @tinora help will be very much appreciated with review / testing/ upgrading one of your own projects once we have a PR

**Comment by williamnoto** [comment]
I can do that.

**Comment by tinora** [comment]
@ptclarke @mkoehnke fyi, I wrote this email to @oligriffiths directly:

Hi Ollie,

you are currently working on a RestKit-Branch (https://github.com/oligriffiths/RestKit.git) in order to free RestKit of the AFNetworking dependency. I’m sure a lot of people including myself much appreciate this effort! I’ve been successfully using RestKit in various projects in the last couple of years. I see no compelling reason to switch to another object mapping framework except for this unfortunate dependency on AFNetworking 1.x. Right now I need to decide which way to go for two upcoming projects a) continue to use RestKit and invest into RestKit and help to free it from AFNetworking or b) drop RestKit in favor of another object mapping framework. I would prefer option a) but this also means I have a certain time pressure and would need to get this done by then end of August (could this be realistic?). 

Now my questions:
- It certainly would make sense to join your current effort and support you making progress. Would you agree and if ‚yes‘ how could we get started as soon as possible?
- What would be the next steps and how could we best coordinate our work?

Regards,
Tino

**Comment by oligriffiths** [comment]
Hi Tino

Would sure appreciate the help. Progress got somewhat stunted over the last couple of months due to me starting a new job. 

Happy to hop on a Skype call sometime to discuss. 

Thoughts Peter?

Oli

**Comment by tinora** [comment]
@oligriffiths @mkoehnke @segiddins 
A Skype call would be perfect the earlier the better feel free to contact me. My Skype id is rachui_ahrensburg. We (my colleague @mkoehnke will join us as well) are located in the north of Germany. What timezone are you in? Today we'll still be available for the next 3-4 hours. Otherwise tomorrow. 

-Tino

**Comment by ptclarke** [comment]
@oligriffiths @tinora @mkoehnke
This is good, we should talk, let's try tomorrow 24 June 12:00 NYC time which will be 18:00 in Germany. I will send a calendar invite.

**Comment by tinora** [comment]
@ptclarke @oligriffiths @mkoehnke
6pm Germany time would be fine given that @oligriffiths will be joining us as well. Will you @oligriffiths?
Tino

**Comment by ptclarke** [comment]
@mkoehnke @tinora @oligriffiths 
Oli has accepted, please let me know your email will send you an invite also.

**Comment by tinora** [comment]
@ptclarke tino.rachui@googlemail.de (as stated in my github profile page) @mkoehnke will make his email visible as well (pls have a look at his page)

**Comment by ptclarke** [comment]
@tinora (email to your googlemail.de address is bouncing)
Have added a brief WIKI to Oli's fork documenting test setup: Setup and run RestKit XCTests. More than happy to help if you have any questions but I think for you it will be fairly straightforward.
All tests complete OK against the master branch.

**Comment by tinora** [comment]
@ptclarke Weird first_name dot last_name at googlemmil.com is correct. Thanks we'll have a look at your wiki entries. I'm about to test Oli's fork today in a project. If time permits I'll also try to run the tests.
