### ISSUE TITLE
NSURLErrorDomain Code=-1002 "unsupported URL" in iOS 8.1

### ISSUE THREAD

**Issue by antoinebis** [RestKit/RestKit#2060]
Hi all,

So everything was working fine in iOS <= 7 until this 8.1 came out. For some reason, I keep getting this error whenever I do something like:

    NSURLRequest *request = [[RKObjectManager sharedManager] requestWithObject:nil method:RKRequestMethodGET path:[NSString stringWithFormat:@"%@/api/rest/deleteddepartments/%@", _baseURL, _dateFilterCreation] parameters:nil];

    RKObjectRequestOperation *operation = [[RKObjectRequestOperation alloc] initWithRequest:request responseDescriptors:responseDescriptors];
    [operation setCompletionBlockWithSuccess:^(RKObjectRequestOperation *operation, RKMappingResult *result)
    {....}

Note that _baseURL is for example: https://api.example.com

The error is the following:

2014-10-24 16:37:43.440 XXXX[397:19080] E restkit.network:RKObjectRequestOperation.m:213 GET '(null)' (0 / 0 objects) [request=0.0108s mapping=0.0000s total=0.0149s]: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo=0x170bad50 {NSUnderlyingError=0x15ff4140 "unsupported URL", NSLocalizedDescription=unsupported URL}

**Comment by sevwandil** [comment]
Any help regarding this issue? I'm also getting the same Error

**Comment by kocyigityunus** [comment]
this can happen from the url with contains space character. make sure your url not starts with a space character.

**Comment by andrewhavens** [comment]
I ran into this error when I specified my base URL with a variable that accidentally contained a new line.

**Comment by suxiaolin** [comment]
This error is so kengdie.

**Comment by antoinebis** [comment]
Hey guys,

If I recall, it is @andrewhavens is right. Make sure your baseURL is fine.
