### ISSUE TITLE
Performance issues when mapping nested objects

### ISSUE THREAD

**Issue by carllindberg** [RestKit/RestKit#2065]
In a project I'm on, we have recently been trying to track down some performance issues, and one of the biggest culprits has turned out to be RestKit mapping performance, particularly when mapping objects which have a bunch of nested children (and grandchildren etc.).   We have one network query which returns about 500K of JSON (when formatted), with about 70 top level objects, and it is taking 3.5 - 3.8 seconds to simply do the mapping on the device.  It looks like it takes about 0.1 seconds to parse the JSON into an NSDictionary, so the rest of the time is pure RestKit.   While it is a somewhat substantial amount of work to do, it feels like RestKit is taking at least an order of magnitude longer than it feels like it "should".  I am not using CoreData; just regular NSObjects.  We are using RestKit 0.23.1.  We upgraded from 0.10.x not all that long ago, but the problem query is new code, so I don't know how it would have performed using the old codebase.

This has been noted before... #1788 is still open, and shows that a somewhat similar toolkit called EasyMapping performs about an order of magnitude faster with the same basic model, and hand-parsing was an order of magnitude faster still.  While an abstract framework would obviously take more time than hand-parsing, 100x seems like a pretty stiff penalty.  And while RestKit most definitely provides many more features than EasyMapping at first glance, it does feel like those features should not incur a 10x cost, particularly if not using them.

The same issue was recently brought up in #2012, which provided a nice testing app to demonstrate the issues (which I will use), though the issue was closed.  The performance seems more like a "bug" than a usage question though, so I'm adding this issue :-)

I've done some profiling and looking through the code.  There is no really obvious a-ha area that I can see... it's pretty obvious a lot of care has been taken in regards to performance, but the end result still seems lacking.  It is probably going to take a number of small fixes, and maybe some internal redesign, to really improve things I fear.    I have been experimenting and have some small code changes which would help... I've improved our timings so far by maybe 35-40%.  It's a decent amount but still a long ways from what I was hoping for.  I'll post some pull requests separately, and link them back here.

One gut feeling is that too many objects are created during the mapping process.  That, and possibly too many autorelease pools (most of them are hidden, but they are there).  But I may just be misunderstanding something as well, so was hoping to discuss some possible improvements to see what the authors (and others) might think.  And if anyone else has any ideas to try :-)

A couple more notes on my data set:  When I run on the simulator, it takes about 0.6 seconds, and of course mobile devices are much much slower.   Since the i386 has a relatively unoptimized ObjC runtime, the retain/release thrash is a actually major part of the time.  A fix which saved 20% on there (by creating many fewer temporary objects) saved only maybe 5% on the ARM device, which was kind of interesting (presumably due to tagged pointers being used for retain/release).  Still, avoiding the creation of temporary objects, for code called a _lot_, should help performance quite a bit.  The malloc and free are avoided, they never get into an autorelease pool, etc., etc.  A few of my fixes are along those lines, but I think there are lots of similar places left where things could be improved that I may not have found yet.  Those can be hard to pinpoint in the profiler since the associated costs can be distributed across multiple other methods (alloc one place, autorelease pool somewhere else, and dealloc in a third, etc.).

For others looking at the thread... if your objects do not implement validateValue:forKey:, you can turn off the performsKeyValueValidation property on RKObjectMapping.  That can save up to 10% of the total time.  Is there any chance it makes more sense to default that to NO for non-managed-object mappings?  Not a big deal since there is a way we can fix that now.

**Comment by naqi** [comment]
@carllindberg Thanks for sharing code. This dramatically reduced the mapping time for me from average 20-40s to 800ms!

**Comment by liorbraginsky92** [comment]
@carllindberg @naqi Can you guys please help me how to use the above code?
Mapping is getting very slow in my app.
Thanks in advance.
