### ISSUE TITLE
Swift: Mapping String value to Enum

### ISSUE THREAD

**Issue by zdnk** [RestKit/RestKit#2122]
I would like to map json key "subitem_type" to "type" that is enum with String raw values

```
public enum FoodOfferItemType: String {

    case Starter = "starter"
    case Main = "main"
    case Desert = "desert"
    case Vegetarian = "vegetarian"
}

public class FoodOfferItem: NSObject {

    public var id: Int?
    public var type: FoodOfferItemType?
    public var text: String?

}

        let foodOfferItemMapping = RKObjectMapping(forClass: FoodOfferItem.self)
        foodOfferItemMapping.addAttributeMappingsFromDictionary([
            "id": "id",
            "subitem_type": "type",
            "text": "text",
        ])
```

**Comment by mozeryansky** [comment]
I wrote a wiki page giving an example of NSString to NS_ENUM (enum) types using a value transformer:
https://github.com/RestKit/RestKit/wiki/RKValueTransformer-Example%3A-Mapping-NSString-to-NS_ENUM

Nothing is too complicated, it should be easily portable to swift.

**Comment by dincho** [comment]
> I would if I knew how to do it properly in Swift.

:+1:

**Comment by kpavankotesh** [comment]
I am trying to write the same in swift, but the output value is constant `let`. I get this warning. Any help @mozeryansky  @segiddins ?

<img width="1328" alt="RKValueTransformer in swift" src="https://user-images.githubusercontent.com/1728799/55059382-d0349680-5094-11e9-8f3d-1cf1e8354b69.png">

**Comment by mozeryansky** [comment]
Wow, it's been about 4 years since my comment. Well, all parameters are lets unless they're marked as `inout`, try that. I haven't used RestKit since my last comment, so I'm not sure how `transformationBlock` is defined in Swift.
