### ISSUE TITLE
registerRequestOperationClass not firing overrided custom method

### ISSUE THREAD

**Issue by RyanCodes** [RestKit/RestKit#2126]
I followed http://blog.higgsboson.tk/2013/09/03/global-request-management-with-restkit/  to the T. and my super method is not being fired when the network call comes back with an error it is calling the parent RKObjectRequestOperation's setCompletionBlockWithSuccess not CustomRKObjectRequestOperation's

Any ideas?

**Comment by RyanCodes** [comment]
Figured it out if you are usingRKManagedObjectRequestOperation.h make sure you register a subclass of that as well

**Comment by YBthebest** [comment]
@RyanCodes could you detail what exactly is needed to make it work with a ManagedObjectRequest? When you say "register a subclass of that as well", what do you put into that subclass? Two identical subclasses, but of different classes? I'm just facing the same issue right now and looking for a simple solution! Thanks a lot.
