### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x00000000

### ISSUE THREAD

**Issue by oNguyenTaCuong** [RestKit/RestKit#2131]
I running my app on iPhone 6 Plus. But i have an issue with RestKit as command below

Thread : com.apple.main-thread
0  libsystem_c.dylib              0x33f2ae26 __vfprintf + 9373
1  libsystem_c.dylib              0x33f2585d __sfvwrite + 492
2  libsystem_c.dylib              0x33f3f009 __v2printf + 504
3  libsystem_c.dylib              0x33eed049 _vsnprintf + 340
4  libsystem_c.dylib              0x33eeceed vsnprintf + 72
5  libsystem_c.dylib              0x33f450ab __snprintf_chk + 22
6  libsystem_asl.dylib            0x33edb11f asl_string_append_char_no_encoding + 106
7  libsystem_asl.dylib            0x33edb429 asl_string_append_internal + 732
8  libsystem_asl.dylib            0x33edae85 asl_msg_to_string_raw + 188
9  libsystem_asl.dylib            0x33edab2f _asl_send_message + 1218
10 libsystem_asl.dylib            0x33edbd3f _asl_lib_vlog + 306
11 libsystem_asl.dylib            0x33edbe6d asl_vlog + 36
12 QuartzCore                     0x2906aec5 x_logv + 228
13 QuartzCore                     0x29139655 x_log_err + 32
14 QuartzCore                     0x2904b001 CA::Render::Shmem::new_shmem(unsigned long) + 196
15 QuartzCore                     0x2904aee7 CA::Render::Shmem::new_bitmap(unsigned int, unsigned int, unsigned int, unsigned int) + 114
16 QuartzCore                     0x29034863 CABackingStoreUpdate_ + 1038
17 QuartzCore                     0x29117c89 ___ZN2CA5Layer8display_Ev_block_invoke + 52
18 QuartzCore                     0x29034449 x_blame_allocations + 88
19 QuartzCore                     0x290340f9 CA::Layer::display_() + 1160
20 QuartzCore                     0x290185b1 CA::Layer::display_if_needed(CA::Transaction*) + 200
21 QuartzCore                     0x29018275 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
22 QuartzCore                     0x29017c51 CA::Context::commit_transaction(CA::Transaction*) + 224
23 QuartzCore                     0x29017a55 CA::Transaction::commit() + 324
24 QuartzCore                     0x2901192d CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 56
25 CoreFoundation                 0x260fad95 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
26 CoreFoundation                 0x260f8453 __CFRunLoopDoObservers + 278
27 CoreFoundation                 0x260f885b __CFRunLoopRun + 914
28 CoreFoundation                 0x260463c1 CFRunLoopRunSpecific + 476
29 CoreFoundation                 0x260461d3 CFRunLoopRunInMode + 106
30 GraphicsServices               0x2d3fe0a9 GSEventRunModal + 136
31 UIKit                          0x29655fa1 UIApplicationMain + 1440
32 MyApp                    0x000ed347 main (main.m:15)

=============================================================================

Thread : Crashed: com.apple.NSURLConnectionLoader (com.apple.root.default-qos.overcommit)
0  libsystem_platform.dylib       0x3400cb7a _platform_memmove + 185
1  CFNetwork                      0x25ba02c7 HTTPReadFilter::doPlainRead(StreamReader*, unsigned char*, long, CFStreamError*, unsigned char*) + 178
2  CFNetwork                      0x25ba011b HTTPReadFilter::_streamImpl_Read(unsigned char*, long, CFStreamError*, unsigned char*) + 394
3  CFNetwork                      0x25b87d73 CoreStreamBase::_streamInterface_Read(unsigned char*, long) + 98
4  CFNetwork                      0x25c0b3a3 HTTPNetStreamInfo::_streamImpl_Read(__CFReadStream*, unsigned char*, long, CFStreamError*, unsigned char*) + 306
5  CFNetwork                      0x25c79c3d CFNetworkReadStream::httpStreamRead(__CFReadStream*, unsigned char*, long, CFStreamError*, unsigned char*, void*) + 44
6  CoreFoundation                 0x2606c1a9 CFReadStreamRead + 328
7  CFNetwork                      0x25c0bee9 HTTPNetStreamInfo::_readStreamClientCallBack(__CFReadStream*, unsigned long) + 128
8  CFNetwork                      0x25c79d57 CFNetworkReadStream::_readStreamClientCallBackCallBack(__CFReadStream*, unsigned long, void*) + 38
9  CoreFoundation                 0x260ab6d7 _signalEventSync + 146
10 CoreFoundation                 0x260ab633 _cfstream_shared_signalEventSync + 342
11 CoreFoundation                 0x260fad57 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 14
12 CoreFoundation                 0x260fa167 __CFRunLoopDoSources0 + 218
13 CoreFoundation                 0x260f87cd __CFRunLoopRun + 772
14 CoreFoundation                 0x260463c1 CFRunLoopRunSpecific + 476
15 CoreFoundation                 0x260461d3 CFRunLoopRunInMode + 106
16 CFNetwork                      0x25bfb957 +[NSURLConnection(Loader) _resourceLoadLoop:] + 486
17 Foundation                     0x26e44b5b __NSThread__main__ + 1118
18 libsystem_pthread.dylib        0x34012e93 _pthread_body + 138
19 libsystem_pthread.dylib        0x34012e07 _pthread_start + 118

=============================================================================

Any suggestions how I can determine the cause?

Thanks.

**Comment by segiddins** [comment]
I don't even see RestKit in that backtrace. You'll need to debug this like any other crash. When you do so, feel free to reopen this issue with your findings.
