### ISSUE TITLE
Unmatched entity descriptions causing problems in RKManagedObjectMappingOperationDataSource

### ISSUE THREAD

**Issue by sixten** [RestKit/RestKit#2134]
I've finally tracked down a problem that's been plaguing me for a couple of days in trying to start writing some unit tests around some networking code in one of our apps that I'm planning to refactor soon.

In my test code, I'm spinning up a Core Data stack with the (model from the working app, and new stores), building an object manager from that, and firing an `RKManagedObjectRequestOperation` (that is stubbed out with Nocilla). Everything worked fine up until the point where the operation attempted to `-obtainPermanentObjectIDsForInsertedObjects:`. That would fail, with Core Data complaining that it didn't know how to assign the entities to the persistent stores.

Performing the analogous work myself—creating a private MOC, adding some new entities, and obtaining IDs for them—worked fine.

Ultimately, it looks like the problem lies in `-mappingOperation:targetObjectForRepresentation:withMapping:inRelationship:`, where it inserts new managed objects. Currently, it's using the `NSEntityDescription` from the entity mapping. If I change that code to first call `+[NSEntityDescription entityForName:inManagedObjectContext:]`, and to use that result, everything works fine.

A couple of months ago, we ran into a very similar problem with `RKManagedObjectDeletionOperation`, where creating the fetch requests with the `NSEntityDescription` from the entity mapping would fail, but replacing that line with this code worked just fine:

```
NSFetchRequest *fetchRequest = [NSFetchRequest fetchRequestWithEntityName:[entityMapping.entity name]];
```

The latter issue, at least, we saw in the running app. The former might be particular to my code being in a unit test, perhaps. I would not be at all surprised if the fact that our app uses two persistent stores might have something to do with it, but that should be a supported configuration.

I'm happy to submit a pull request with the (simple) changes that I made, but you guys would probably (understandably) want corresponding tests added to RestKit's own suite, and I'm not at all up to speed on where and how that should happen. Nor am I 100% sure what the exact circumstances are that create this problem.

**Comment by segiddins** [comment]
Yeah, I'd need test coverage to be able to merge such a PR.

**Comment by sixten** [comment]
OK. Before I go burn a bunch more time: are the instructions that are in the wiki for setting everything up, and being able to run the test suite, up to date?

**Comment by segiddins** [comment]
Just run bundle exec pod install

-Samuel E. Giddins

On Jan 15, 2015, at 5:52 PM, Sixten Otto <notifications@github.com> wrote:

OK. Before I go burn a bunch more time: are the instructions that are in the wiki for setting everything up, and being able to run the test suite, up to date?

**Comment by sixten** [comment]
Yeah, it's a little more complicated than that (especially for folks, like me, that don't use Ruby much). The [README in the Tests directory](https://github.com/RestKit/RestKit/blob/c17a180b729028223d2825b96f707f1cbe5a06a9/Tests/README.md) was helpful, but that information seems like it should really either be linked from, or incorporated into, the main [contribution instructions](https://github.com/RestKit/RestKit/wiki/Contributing-to-RestKit). That latter document doesn't really include any of the information about the setup necessary after checking out the code.

**Comment by segiddins** [comment]
Agreed, do you want to add them?

**Comment by sixten** [comment]
Frankly, that's not a task I was looking for, but I can maybe take a stab at it.

I was able to get the tests building and running. Everything came up green except for one test; expected?

```
Test Case '-[RKObjectRequestOperationTest testCopyingOperation]' started.
2015-01-16 11:00:11.061 xctest[38956:10105903] /Users/sotto/Projects/_shared/RestKit/Tests/Logic/Network/RKObjectRequestOperationTest.m:723 expected: a truthy value, got: 0, which is falsy
/Users/sotto/Projects/_shared/RestKit/Tests/Logic/Network/RKObjectRequestOperationTest.m:723: error: -[RKObjectRequestOperationTest testCopyingOperation] : expected: a truthy value, got: 0, which is falsy
2015-01-16 11:01:31.299 xctest[38956:10105903] /Users/sotto/Projects/_shared/RestKit/Tests/Logic/Network/RKObjectRequestOperationTest.m:731 expected: not nil/null, got: nil/null
/Users/sotto/Projects/_shared/RestKit/Tests/Logic/Network/RKObjectRequestOperationTest.m:731: error: -[RKObjectRequestOperationTest testCopyingOperation] : expected: not nil/null, got: nil/null
```

I've added a couple of new tests for the failures I was seeing; whether or not they fit, stylistically, you'd be a better judge. (And I won't be offended if they need some work.) I'll open a PR shortly.

**Comment by segiddins** [comment]
Closed by https://github.com/RestKit/RestKit/pull/2139.
