### ISSUE TITLE
Make setting shared object manager optional/explicit

### ISSUE THREAD

**Issue by sixten** [RestKit/RestKit#2136]
Right now, any time a new `RKObjectManager` is created with `-initWithHTTPClient:`, it will automatically install itself as the global shared object manager if there isn't one already. While this is convenient for many, it makes taking explicit control over managing the RestKit stack very difficult. It would be great if there were some way to make this a more directly controllable process, or at least a way to create an object manager without having it opt in to the shared role.

**Comment by segiddins** [comment]
If you want to use individual `RKObjectManagers`, just retain them and don't refer to the `sharedManager`.

**Comment by sixten** [comment]
… and as long as I can rely on there being no places in our app—or in RestKit itself—where something just assumes that whatever's in the shared instance is OK to use, I guess that'll work. :-/

**Comment by segiddins** [comment]
Nothing in RestKit uses the sharedManager

-Samuel E. Giddins

On Jan 15, 2015, at 5:50 PM, Sixten Otto <notifications@github.com> wrote:

… and as long as I can rely on there being no places in our app—or in RestKit itself—where something just assumes that whatever's in the shared instance is OK to use, I guess that'll work. :-/
