### ISSUE TITLE
RESTKit failling to map array property properly

### ISSUE THREAD

**Issue by rlugge** [RestKit/RestKit#2140]
I can an object, lets call it 'Foo', that contains two relevant properties.  Those properties are both arrays containing other mapped objects (Call them Bar1 and Bar2).  One of them functions properly, the other one is throwing the error:  `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (Bar2)'`

I have Foo mapped like so:

    RKObjectMapping *fooMapping=[RKObjectMapping mappingForClass:[Foo class]];
    [fooMapping addRelationshipMappingWithSourceKeyPath:@"bar1array" mapping:[Bar1 generateMapping]];
    [fooMapping addRelationshipMappingWithSourceKeyPath:@"bar2array" mapping:[Bar2 generateMapping]];
   
Bar1 and Bar2 generateMapping are not identical methods, but other than changing of property names / quantity of properties, can be considered identical.  As Bar2 is the one that is failing, I'll use bar2 as the sample code:

    RKObjectMapping *bar2Mapping=[RKObjectMapping mappingForClass:[Bar2 class]];
    [bar2Mapping addAttributeMappingsFromDictionary:@{
                                                                       @"ommitedProperties":@"AreOmmited"
                                                                       }];
    return bar2Mapping;

What's really frustrating is that I even turned the debug level up to maximum (trace), and I can *see* that RESTKit is executing the mapping for Bar2, but the end result is:

    2015-01-18 22:06:08.199 West Pak QC[453:161549] T restkit.object_mapping:RKMappingOperation.m:690 Mapped relationship object from keyPath 'bar2array' to 'bar2array'. Value: (
        "<Bar2: 0x1a129260>",
        "<Bar2: 0x16886760>",
        "<Bar2: 0x1a127340>",
        "<Bar2: 0x157bfa80>",
        "<Bar2: 0x1686cd20>"
    )

As far as I can tell, and for no apparent reason, RESTKit is mapping the object, then discarding the mapping in favor of the original.  I've spent... far too much time debugging it this far, and I am making exactly zero further progress forward at this point.

**Comment by segiddins** [comment]
Is there any way you could write a failing unit test that demonstrates the issue?

**Comment by rlugge** [comment]
@segiddins Sadly, I'm here because I can't figure out why it's failing.  I'll see if I can reproduce in a test project or something.

**Comment by orenk86** [comment]
I ran into the same problem, @rlugge . Eventually, I mapped whatever is supposed to be a NSArray as a NSSet.
Then you can get and set the NSArray or NSMutableArray like so:
NSArray *theArray = [theSet allObjects];
NSMutableArray *theMutableArray = [NSMutableArray arrayWithArray:[theSet allObjects]];
NSSet *theSet = [NSSet setWithArray:theArray];

Hope this helps

**Comment by rlugge** [comment]
@orenk86 thanks for the thought, unfortunately it didn't work.  Changing over to using a set didn't fix the mapping issues.

**Comment by orenk86** [comment]
@rlugge that's strange... it's working flawlessly in my apps.
Don't know if it'll change anything, but try setting the NSSet as a (nonatomic, copy) property. That's how the sets are declared in my apps...

**Comment by rlugge** [comment]
@orenk86 

Actually, a co-worker just helped me find the problem.  It's insanely stupid.

RESTkit is actually doing *exactly* what I told it to.  It's mapping from Bar2... to Bar2.

`RKObjectMapping *bar2Mapping=[RKObjectMapping mappingForClass:[Bar2 class]];`

This is actually my upload mapping, it needs to map NSMutableDictionary, not Bar2.  Oops.
