### ISSUE TITLE
Upload image crash

### ISSUE THREAD

**Issue by Vincent-z** [RestKit/RestKit#2146]
**The upload Code:**
`UIImage *image = [UIImage imageNamed:@"refreshFailed.png"];`

`NSMutableURLRequest *request = [[RKObjectManager sharedManager] multipartFormRequestWithObject:nil method:RKRequestMethodPOST path:@"/user/update" parameters:@{@"type" : @"13"} constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
        [formData appendPartWithFileData:UIImagePNGRepresentation(image)
                                    name:@"icon_data"
                                fileName:@"icon_data"
                                mimeType:@"image/png"];
    }];`

`RKObjectRequestOperation *op = [[RKObjectManager sharedManager]objectRequestOperationWithRequest:request success:^(RKObjectRequestOperation *operation, RKMappingResult *mappingResult) {
        NSLog(@"%@", mappingResult);
    } failure:^(RKObjectRequestOperation *operation, NSError *error) {
        NSLog(@"%@", error);
    }];  `

   ` [op.HTTPRequestOperation setUploadProgressBlock:^(NSUInteger bytesWritten, long long totalBytesWritten, long long totalBytesExpectedToWrite) {
        NSLog(@"%f", totalBytesWritten * 1.0 / totalBytesExpectedToWrite);
    }];`

  `  [[RKObjectManager sharedManager]enqueueObjectRequestOperation:op];`

After uploaded  it crashed in
method:`- (BOOL)validateValue:(id *)value atKeyPath:(NSString *)keyPath` 
line:`success = [destinationObject validateValue:value forKeyPath:keyPath error:&validationError];`

I don't know why.

**Comment by Sajjon** [comment]
@Vincent-z I have this problem too, did you solve it?

**Comment by Sajjon** [comment]
Ah! I think this is the problem:
http://stackoverflow.com/a/23337467/1311272
