### ISSUE TITLE
AFNetworking 2.5 Upgrade

### ISSUE THREAD

**Issue by sarmadali20** [RestKit/RestKit#2150]
Is it possible to use AFNetworking 2.5 ? I am using cocapods and have another library which is using 2.5 of AFNetworking but restkit is using 1.3

I can help with this if it's already planned.

Thanks

**Comment by segiddins** [comment]
There are a bunch of issues open about this, which you should've found before opening this one, but the gist of things is that we want to nuke the AFN dependency entirely for 1.0.
