### ISSUE TITLE
Not mapping nested array in response

### ISSUE THREAD

**Issue by MarkMolina** [RestKit/RestKit#2151]
Trying to map a response like

```{
	"customer": {
		"first_name": "John",
		"last_name": "Doe",
		....
	},
	"orders": [],
	"devices": [{
		"validated": false,
		"device_id": "XXXX-XXXX-XXXX",
		"device_type": null
	}],
	"id": "54d1fe8650747b05339f2f81",
	"participants": [{
		....
	}],
	"primary_email": null,
	"emails": [{
		"validated": false,
		"primary": 0,
		"email": "awefwa@wefw.yhj"
	}]
}```

But for some reason RestKit fails to map the 'emails' part.

* Starting mapping operation...
* Mapping one to many relationship value at keyPath 'emails' to 'emails'
* Starting mapping operation...
* Finished mapping operation successfully...
* Destination object 
accountId : 54d1fe8650747b05339f2f81
emails : (null)
devices : (null)
participants : (null)
orders : (null) rejected attribute value (
    "\naddress : awefwa@wefw.yhj\nvalidated : 0\nprimary : 0"
) for keyPath emails. Skipping...

Later on devices for example gets mapped correctly. Weird thing is that an earlier request does map the email part

```{
	....
	"emails": [{
		"validated": false,
		"validation_token": "f735dbe9098949341eddfef56157a20471254dd6",
		"primary": 0,
		"email": "awefwa@wefw.yhj"
	}]
}```

Mapping all looks fine

Asked to map source object {
    customer =     {
        "first_name" = fawefawef;
        "last_name" = wefa;
       ....
    };
    devices =     (
                {
            "device_id" = "XXXX-XXXX-XXXX";
            "device_type" = "<null>";
            validated = 0;
        }
    );
    emails =     (
                {
            email = "awefwa@wefw.yhj";
            primary = 0;
            validated = 0;
        }
    );
    id = 54d1fe8650747b05339f2f81;
    participants =     (
                {
            ....
        }
    );
    "primary_email" = "<null>";
} with mapping <RKObjectMapping:0x7fabca49e400 objectClass=XXAccount propertyMappings=(
    "<RKRelationshipMapping: 0x7fabca415ff0 emails => emails>",
    "<RKRelationshipMapping: 0x7fabca0c3410 devices => devices>",
    "<RKRelationshipMapping: 0x7fabca0d4630 participants => participants>",
    "<RKRelationshipMapping: 0x7fabca4867e0 orders => orders>",
    "<RKAttributeMapping: 0x7fabca4992b0 id => accountId>"
)>


Why does RestKit log this? A don't really know what it means and can't find any documentation.

**rejected attribute value (
    "\naddress : awefwa@wefw.yhj\nvalidated : 0\nprimary : 0"
) for keyPath emails. Skipping...**

**Comment by Appsido** [comment]
Can you provide your mappings definition?

**Comment by MarkMolina** [comment]
Well.. Tried to do that dynamically for all requests based on the model.

```+ (RKObjectMapping*)getResponseMappingForModel:(Class)class withObjectManager:(RKObjectManager*)objectManager
{
    RKObjectMapping *mapping = nil;
    
    mapping = [RKObjectMapping mappingForClass:class];
    
    if (mapping) {
        
        // Turn modelAttributes belonging to class into a NSMutableDictionary that RestKit can use
        NSMutableArray *modelAttributes = [class getModelAttributes];
        NSMutableDictionary *attributeDictionary = [NSMutableDictionary new];
        
        for (int n = 0; n < modelAttributes.count; n++) {
            
            TBModelAttribute *modelAttribute = modelAttributes[n];
            if(modelAttribute.callType==CallTypeResponse || modelAttribute.callType==CallTypeAll) {
                
                if (modelAttribute.usingModel==nil) {
                    // Not using a model, just return standard mapping
                    [attributeDictionary setValue:modelAttribute.classProperty forKey:modelAttribute.jsonKey];
                } else {
                    // We need relationship mapper
                    [mapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:modelAttribute.jsonKey
                                                                                            toKeyPath:modelAttribute.classProperty
                                                                                          withMapping:[self getResponseMappingForModel:modelAttribute.usingModel withObjectManager:objectManager]]];
                }
            }
        }
        
        [mapping addAttributeMappingsFromDictionary:attributeDictionary];
    }
    
    return mapping;
}```


Bit hard to understand but this used to work fine. Also when breaking it down and stepping through the mapping process everything looks fine as well.

**Comment by Appsido** [comment]
I had a similar issue no longer than yesterday. You may have look here : http://stackoverflow.com/questions/28257259/restkit-0-24-mapping-using-addconnectionforrelationship/28295348?noredirect=1#comment44960947_28295348 <http://stackoverflow.com/questions/28257259/restkit-0-24-mapping-using-addconnectionforrelationship/28295348?noredirect=1#comment44960947_28295348>

Because since your data mapping is dynamic and no insight on the getModelAttribute it’s difficult to provide more support

**Comment by MarkMolina** [comment]
Thanks for the info. I will check your post. I'll also try to log as much info as I can on the mapping.

**Comment by MarkMolina** [comment]
Apparently the mapping of the array goes fine. Looks like it's going wrong when setting the relation

* Found transformable value at keyPath 'email'. Transforming from class '__NSCFString' to 'NSString'
* Mapping attribute value keyPath 'email' to 'address'
* Mapped attribute value from keyPath 'email' to 'address'. Value: asdf123@wet.tu
* Found transformable value at keyPath 'validated'. Transforming from class '__NSCFBoolean' to 'NSNumber'
* Mapping attribute value keyPath 'validated' to 'validated'
* Mapped attribute value from keyPath 'validated' to 'validated'. Value: 0
* Found transformable value at keyPath 'primary'. Transforming from class '__NSCFNumber' to 'NSNumber'
* Mapping attribute value keyPath 'primary' to 'primary'
* Mapped attribute value from keyPath 'primary' to 'primary'. Value: 0
* Finished mapping operation successfully...
* Found transformable value at keyPath 'emails'. Transforming from class '__NSArrayM' to 'NSArray'
* Destination object 
accountId : 54d22edf50747b05339f2fa2
emails : (null)
devices : (null)
participants : (null)
orders : (null) rejected attribute value (
    "\naddress : asdf123@wet.tu\nvalidated : 0\nprimary : 0"
) for keyPath emails. Skipping...

**Comment by carllindberg** [comment]
"rejected attribute value" means that the validateValue:forKeyPath:error: implementation returned NO.   If you have custom validation routines in there, I would check those implementations.  You could set performsKeyValueValidation to NO on the mapping to avoid that check, but presumably there is a reason it is returning NO.  RestKit should be logging the validation error immediately after the log above, which should give further info.

**Comment by MarkMolina** [comment]
Well the there's really no other error in there. Before the skipping error Restkit just does it's normal mapping and that all looks fine. I compared it with the mapping of "devices" in our  request since it's the same structure. 

Added the log from that request here
http://pastebin.com/rXNgXDyb

**Comment by carllindberg** [comment]
RestKit is handling it correctly.  -validateValue: is returning NO, therefore the assignment should be skipped.  The implementation of -validateValue: is beyond RestKit's control.

It looks like RKLogValidationError() is called with the underlying error, which should give you more information on the problem.  However if CoreData is defined, and the error is *not* of the NSCocoaErrorDomain, then nothing will get logged.  That probably is a bug which should be fixed.  You could modify that function in RestKit to always log the error (such as what the non-CoreData situation does), and run with that -- it should give you better information.  That part should probably be a RestKit fix -- just log out the error if it's not a NSCocoaErrorDomain as expected; right now it's silent and that is critical information.  Custom implementations can always return errors with custom domains.

**Comment by MarkMolina** [comment]
Yep... Custom implementations -_-
