### ISSUE TITLE
 New RESTKit Tutorial

### ISSUE THREAD

**Issue by bonzoq** [RestKit/RestKit#2160]
I've written a tutorial on using RESTKit with Core Data. Not sure if it's the right place but hope you can help to spread the word: https://medium.com/ios-os-x-development/restkit-tutorial-how-to-fetch-data-from-an-api-into-core-data-9326af750e10

**Comment by segiddins** [comment]
Just retweeted a tweet about it, well done!

**Comment by bonzoq** [comment]
What is your twitter account if you don't mind telling?

**Comment by segiddins** [comment]
`@restkit`
