### ISSUE TITLE
Core Data Concurrency Debugging Crash

### ISSUE THREAD

**Issue by jeffblake** [RestKit/RestKit#2165]
Happens when connecting a foreign key relationship, as shown in this screenshot. I am using the latest source from development.

Scheme:
`-com.apple.CoreData.ConcurrencyDebug 1`

`pod 'RestKit', git: 'https://github.com/RestKit/RestKit.git', branch: 'development'`

![screen shot 2015-02-18 at 11 52 47 am](https://cloud.githubusercontent.com/assets/620564/6255466/fa1af502-b764-11e4-9e3d-618ab8a41b64.png)

**Comment by segiddins** [comment]
A PR to fix this would be much appreciated!
