### ISSUE TITLE
In your Readme.md

### ISSUE THREAD

**Issue by voznesenskym** [RestKit/RestKit#2167]
RKObjectManager *manager = [RKObjectManager managerWithBaseURL:[NSURL URLWithString:@"http://restkit.org"];

should be

RKObjectManager *manager = [RKObjectManager managerWithBaseURL:[NSURL URLWithString:@"http://restkit.org"]];

**Comment by segiddins** [comment]
Would love a PR fixing this!

**Comment by voznesenskym** [comment]
https://github.com/RestKit/RestKit/pull/2168

Cheers!

**Comment by voznesenskym** [comment]
Also, let me know if you are interested in another project collaborator - I've really enjoyed using restkit and wanna help out some more.

**Comment by segiddins** [comment]
@voznesenskym I'm always happy to welcome new contributors to the project!

**Comment by voznesenskym** [comment]
Great. Any outstanding big issues that need taking care of? Or small
bugs...? Or should I just look at issues?

**Comment by segiddins** [comment]
All the issues are here on GitHub.
