### ISSUE TITLE
RestKit & AFOAuth2Manager using CocoaPods

### ISSUE THREAD

**Issue by kyledecot** [RestKit/RestKit#2172]
I'm not really sure where to report this but...I'm trying to install `RestKit` and `AFOAuth2Manager` using CocoaPods:

__Podfile__

```
platform :ios, '8.1'

inhibit_all_warnings!

target 'foobar' do
  pod 'RestKit'
  pod 'AFOAuth2Manager'
end
```

When executing `pod install` I received the following error:
```
Analyzing dependencies

CocoaPods 0.36.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Installing AFNetworking (2.5.1)
Installing AFOAuth2Manager (2.0.0)
Installing FileMD5Hash (0.0.1)

[!] Error installing FileMD5Hash
[!] /usr/local/bin/git checkout -b activated-commit d00c0c51c6d0955d9daf94c30cfd95a219d4914e

fatal: reference is not a tree: d00c0c51c6d0955d9daf94c30cfd95a219d4914e
```

**Comment by segiddins** [comment]
That's an issue with `FileMD5Hash`, not RestKit.

**Comment by mefilt** [comment]
wtf? reskit use FileMD5Hash

**Comment by Mazyod** [comment]
Resolved:

```
target 'AppTarget' do
	pod 'FileMD5Hash', :git => 'git@github.com:Tomusm/FileMD5Hash.git'
	pod 'RestKit'
end
```

I think RestKit devs should evaluate removing this broken dependency, since it's a headache for their users.

**Comment by segiddins** [comment]
RestKit doesn't depend upon FileMD5Hash, so this has nothing to do with RestKit whatsoever.

**Comment by Mazyod** [comment]
Sorry, you are right. I think something is messed up in our setup .. Trying to figure it out

**Comment by maxep** [comment]
I had the same issue, it was because I had a dependency depending on AF 2.+ and RestKit still depends on AF 1.3.4
