### ISSUE TITLE
Avoiding KVO Obervers for RESTKit calls

### ISSUE THREAD

**Issue by aqibmumtaz** [RestKit/RestKit#2173]
Hi RESTKit Team,

Im using RESTKit which works like a charm, but Im stuck in a situation in which I need your expert opinion on how to tackle it.

I m trying to implement updating "dateModified" using KVO Observers as shown here
https://github.com/dvidsilva/everpobre/blob/master/coreData/DVDNoteModel.m

But the problem is this is also being called when RESTKit is fetching data from server and storing it locally in CoreData, which I dont want.

I need to avoid triggering KVO observers only for the RESTKit calls, so when RESTKit fetches data from server it must not get updated with dataModified.

Furthermore I found out that RESTKit calls are being initiated from [RKResponseMapperOperation main] so using [NSThread callStackSymbols] although I m able to successfully track them to avoid KVO Observers, but this solution is functional for Build version only (build version works fine on devices too) but for Release version [NSThread callStackSymbols] isn't returning same symbols leaving RESTKit call untracked.

I am unable to track if current call is RESTKit or my own (in Release).

Is there a way to track if current Thread call is from RESTKit?
or 
Is there a way we could track it using RESTKit NSManagedObjectContext or so?
or any other possible solution?

My aim is simple, I wants to keep modifying "dateModified" for each of my NSManagedObjects (using KVO Observers or so) whenever there is change in it except for RESTKit. once RESTKit is loading data from service for RKEntityMapping objects, its creating NSManagedObjects to persist in Coredata, while doing Coredata operations RESTKit is overwriting "dateModified" in KVO Observers for all NSManagedObjects which are coming from server, which I dont want, there must be some suitable solution to identify RESTKit calls to avoid KVO observers for that particular call.

Further description:
http://stackoverflow.com/questions/28701841/avoiding-kvo-obervers-for-restkit-calls?noredirect=1#comment45704235_28701841

Please answer if you have any possible hint.
Thanks.

**Comment by segiddins** [comment]
No, what you want to do isn't possible using KVO.
