### ISSUE TITLE
Forced to change NSManagedObject subclasses

### ISSUE THREAD

**Issue by besi** [RestKit/RestKit#2181]
I have a project where I have introduced Swift classes.

As soon as I ran the project I ran into this assertion:

>      NSAssert(objectClass, @"Cannot initialize an entity mapping for an entity with a nil managed object class: Got nil class for managed object class name '%@'. Maybe you forgot to add the class files to your target?", [entity managedObjectClassName]);
> See [RKEntityMapping.m:166](https://github.com/RestKit/RestKit/blob/02165a278979095047a98a8d1aa34ca5673395d1/Code/CoreData/RKEntityMapping.m#L166)

With the help of the SO Post [Swift RestKit CoreData - RKEntityMapping nil class for class name](http://stackoverflow.com/questions/26946674) I was able to resolve the issue.

So what I did is update my Swift file with the `objc( )` annotation like so:

```swift
// Issue.swift

import Foundation
import CoreData

// TODO: This was added manually. Not nice.
@objc(Issue)

class Issue: NSManagedObject {

    @NSManaged var repository: Repository
    @NSManaged var responsible: User
    @NSManaged var version: Version

}
```

I am  wondering if there is a better way around this issue. Because as soon as I will update the model and re-generate the classes the correction will be overwritten again.

**Comment by Appsido** [comment]
Either you can create a subclass for that inherit from Issue class and add the @objc() statement or use mogenerator to automate the process

**Comment by ocwang** [comment]
I ran into the same issue after auto-generating a new entity with XCode 7.0. I solved this by going to the Data Model Inspector for the respective entity and deleting the 'Module' field. See SO post for reference: http://stackoverflow.com/questions/25076276/unable-to-find-specific-subclass-of-nsmanagedobject

**Comment by segiddins** [comment]
You can also use the fully qualified class name: `Module.ClassName`.
