### ISSUE TITLE
RKManagedObjectDeletionOperation memory leak

### ISSUE THREAD

**Issue by erichedstrom** [RestKit/RestKit#2182]
I have discovered a leak in my app when using deletion predicates. There seems to be a cycle between the RKManagedObjectDeletionOperation added as an associated object on the mapping operation in -[RKManagedObjectMappingOperationDataSource commitChangesforMappingOperation:error:] and the mapping operation.

![screen shot 2015-03-08 at 3 21 50 pm](https://cloud.githubusercontent.com/assets/1738136/6548007/c62d5810-c5a7-11e4-915a-b449553c8068.png)

If I change the associated object assignment policy from OBJC_ASSOCIATION_RETAIN_NONATOMIC to OBJC_ASSOCIATION_ASSIGN, it breaks the cycle and these objects are all cleaned up after the mapping has finished.

Another fix I feel more comfortable with is to add
    `self.entityMappings = nil;`
at the end of [RKManagedObjectDeletionOperation main]. This also breaks the cycle and allows the mapping-related objects to be cleaned up after the mapping is complete.

Has anyone else run into this or know why the entity mappings would prevent the mapper operation from being released?

**Comment by segiddins** [comment]
Id appreciate a pull request with a fix!
