### ISSUE TITLE
RKResponseDescriptor/RKPathMatcher threading bug?

### ISSUE THREAD

**Issue by brightredchilli** [RestKit/RestKit#2184]
I believe there is a threading bug in RestKit.
The gist to show it is here: https://gist.github.com/brightredchilli/97e194cd352de299e78a
Repo here if you want to run and debug the whole thing. Just clone, pod install and run.
https://github.com/brightredchilli/RestKitTest

Summary:
1. Create response descriptors and mappings to 2 classes, Foo and Bar, with two different path patterns.
2. Make a request for "/foo" and "/bar" repeatedly(from main thread)
3. Observe that sometimes the call sometimes fails because no response descriptors are found, or because the call that's supposed to return Foo returns Bar.

The hypothesis, after a bunch of digging, is that RKPathMatcher is not thread safe, and the \[RKResponseDescriptor matchesURL:\] (which gets called from different threads) uses it. See [RKPathMatcher matchesPath:tokenizeQueryStrings:parsedArguments:]. self.sourcePath is being assigned to here, and if different threads were trying to query different URLs, they would get reassigned.

This is because the dispatch queue for making object requests are concurrent. FWIW, I made the [RKObjectRequestOperation dispatchQueue] serial, and I could not repro the issue(not that this is a good fix). 

Even if we did that, there are still other issues. The -matchesURL calls are still happening outside of the dispatch queue, in methods like [RKObjectManager getObject:path:parameters:success:failure]. In my repo, uncomment [RKTest makeVeryUnsafeBarCall] to see the sparks fly.

Is there something wrong with the way I'm using RestKit? It's hard to believe no one else has run into the issue. For now, it seems that the best thing to do is to make RKPathMatcher thread safe, and that can be done by collapsing the bunch of methods that share the same instance var to a single method, so that values can just be passed to the method. However, I don't know if there are other classes where this is an issue. 

For those out there struggling with this, you might have some luck with a synchronize lock around RKResponseDescriptor matchesPath. With my limited testing this seems to fix the issue.

    - (BOOL)matchesPath:(NSString *)path
    {
        @synchronized(self) {
            if (!self.pathPattern || !path) return YES;
            return [self.pathPatternMatcher matchesPath:path tokenizeQueryStrings:NO parsedArguments:nil];
        }
    }

Thanks to @michaelmorton, who did a lot of groundwork to figure this out.

**Comment by segiddins** [comment]
I believe I recently merged a PR that made RKPathMatcher thread-safe. Can ou check and see if this is fixed on master?

**Comment by brightredchilli** [comment]
Darn. I should have checked with master. Looks like it's all good, thanks! When getting the latest RestKit from master, the tag did not bump(still at 0.24). Can you(or someone) make a new tag for RestKit - so that I can update Cocoapods.

**Comment by segiddins** [comment]
I'm hoping to get one or two more things in before releasing, but this might warrant a quick patch release.

**Comment by brightredchilli** [comment]
@segiddins Do you have a rough timeline on when you'll be able to get to this?(hours or days) I understand if you won't be able to get to it soon, Im just trying to decide if it's worth to patch our fork or wait, since this issue breaks our integration tests.

**Comment by segiddins** [comment]
Feel free to bind against master in the meantime.
