### ISSUE TITLE
Travis build fails to run tests

### ISSUE THREAD

**Issue by vilinskiy-playdayteam** [RestKit/RestKit#2196]
Travis build fails to run tests with following error:
**xcodebuild: error: Failed to build workspace RestKit with scheme RestKitTests.
Reason: The run destination iPad 2 is not valid for Testing the scheme 'RestKitTests'.**

**Comment by segiddins** [comment]
This is a known issue. Please submit s PR if you have a fix for it.

**Comment by vilinskiy-playdayteam** [comment]
I fixed this problem in pending pull request
