### ISSUE TITLE
Concurrency exception thrown

### ISSUE THREAD

**Issue by sarn** [RestKit/RestKit#2201]
I'm debugging an app using the `-com.apple.CoreData.ConcurrencyDebug 1` option. During that debugging session I found that RestKit 0.24.1 crashes on the line `id relationshipValue = [object valueForKeyPath:destinationKeyPath]` of the method `RKManagedObjectsFromObjectWithMappingInfo` inside the `RKManagedObjectRequestOperation.m`. It should be line# 380.

The code gets called by `NSSet *managedObjectsInMappingResult = RKManagedObjectsFromMappingResultWithMappingInfo(mappingResult, self.mappingInfo) ?: [NSSet set];` inside `deleteLocalObjectsMissingFromMappingResult:`

I don't see a crash, if I safeguard the call with a `performBlockAndWait`like the following snipped

    // Proceed with cleanup
    __block NSSet *managedObjectsInMappingResult;
    [self.privateContext performBlockAndWait:^{
        managedObjectsInMappingResult = RKManagedObjectsFromMappingResultWithMappingInfo(mappingResult, self.mappingInfo) ?: [NSSet set];
    }];

**Comment by segiddins** [comment]
Id love a pull request with the necessary fix!

**Comment by sprynmr** [comment]
https://github.com/GrahamDennis/GDCoreDataConcurrencyDebugging

Useful framework here. I see a lot of issues being exposed with it. I think related to a lot of the crashes I'm seeing.

**Comment by sarn** [comment]
`GDCoreDataConcurrencyDebugging` is a nice option, but got dispensable with the new `-com.apple.CoreData.ConcurrencyDebug 1`launch argument introduced with iOS8. More info here: http://oleb.net/blog/2014/06/core-data-concurrency-debugging/

I did a pull request for this issue, but for some reason the Travis build failed. I can't imagine that such a subtle change can break the build and there was no obvious test that failed.

**Comment by sprynmr** [comment]
Interesting. Well at least with the library I was getting warnings all over the place, didn't try with this yet. Looks like your pull just addresses the one spot. Did you see others?

**Comment by sarn** [comment]
No I only saw this one spot. No other issues popped up with `-com.apple.CoreData.ConcurrencyDebug 1`enabled. But I never tried the `GDCoreDataConcurrencyDebugging` library. Could it be that this library creates some "False Positives" as well?
