### ISSUE TITLE
Upgrade AFNetworking 2.5.2

### ISSUE THREAD

**Issue by emmasuzuki** [RestKit/RestKit#2204]
Are there any plan that RestKit will have AFNetworking 2.5.2 integrated in near future ?  
It looks like the latest using 1.3.4

I would like to have 2.5.2 or above specifically for security fix on AFNetworking. 
http://arstechnica.com/security/2015/04/1500-ios-apps-have-https-crippling-bug-is-one-of-them-on-your-device/

**Comment by segiddins** [comment]
No, the goal is to get rid of the AFNetworking dependency entirely.

**Comment by alexandrenascimento** [comment]
There is an estimative to that?

**Comment by segiddins** [comment]
No, but there are many other issues discussing this.

**Comment by mozeryansky** [comment]
From reading through the docs, it seems RestKit Object Mapping is independent of AFNetworking. Is my assumption true?

I would like to use the mapping, just not the networking.

Is this case, we have a lot of networking code (using AFNetworking 2) which returns json or NSDictionary. Which we plan to just pass to restkit to do it's thing.

**Comment by segiddins** [comment]
@mozeryansky correct. That's all currently possible.

**Comment by mozeryansky** [comment]
@segiddins, I've read other comments where you mention you no longer use RestKit at your job. What do you use currently?

**Comment by segiddins** [comment]
I'm not building full apps, otherwise I would be using RestKit.

**Comment by mozeryansky** [comment]
Ok, thanks for the quick responses. I will be using the Object Mapping.
