### ISSUE TITLE
Explain patchObject behaviour

### ISSUE THREAD

**Issue by samskiter** [RestKit/RestKit#2205]
Hi,

Trying to evaluate ResKit at the minute. The rest API I'm using makes use of 'PATCH' methods to update objects. How does RestKit handle patching? I've tried to dig through the source but got quite lost. Does a patch request by default just send the whole object, or does RestKit do some KVO magic to track what has changes on an object?

Sorry for posting this to issues,

Sam

**Comment by segiddins** [comment]
RestKit will serialize whatever your response serializer says to serialize -- there's no magic involved.

**Comment by samskiter** [comment]
I haven't been able to find a reference to a response serializer, is this the `RKRequestDescriptor` ?

**Comment by segiddins** [comment]
Sorry, I meant response descriptor.
