### ISSUE TITLE
AFNetworking 1.3.4 and SSL issue fixed in 2.5.3

### ISSUE THREAD

**Issue by cossorn** [RestKit/RestKit#2208]
Given that AFNetworking 2.x integration seems to have been ignored in RestKit, so any apps using RestKit are stuck with AF v1.3.4, does anyone have observations on whether the recently exposed SSL issue therefor also applies to RestKit users (unless pinning is in force) ? 
Maybe getting to current AFNetworking v2.5.3 should be a priority ?

http://arstechnica.com/security/2015/04/24/critical-https-bug-may-open-25000-ios-apps-to-eavesdropping-attacks/

**Comment by segiddins** [comment]
Those issues only affected the 2.x series of releases.

**Comment by cossorn** [comment]
The bug (of having a poor default setting, on whether to validate the domain name) is only in 2.x.

However, the issue remains (for unpinned apps) that RestKit 1.3.4 does not attempt to validate that the domain supplied in the ServerTrust certificate path actually matches the domain of the node that the app was attempting to open the URL for. This means that every RestKit app which does not have pinned certificates is vulnerable to MITM where a valid certificate (but for a different domain) is used by the MITM.. **this is a major security hole, which should not be neatly stuffed away as "closed" or SEP (Someone Else's Problem) because it is in AFNetworking. The dependency of RestKit on particular versions of AFNetworking IS in the RestKit area.**

I tested this yesterday, connecting to an internal server https://dev.com which has a current valid certificate, but the certificate is for one of our clients i.e. should not be valid for opening this URL (cert is for *.<clientname>.com.au)

With AFNetworking 1.3.4 this allowed the connection.
I patched into AFURLConnectionOperation.m a bit of the code from the same class in 2.5.3, 
and grabbed the 2.5.3 code from AFSecurityPolicy.m (simplified, we never allow invalid certificates and always want to verify the domain name) merged in 
static BOOL AFServerTrustIsValid() and
- (BOOL)evaluateServerTrust:() forDomain:
and hey-presto, the connection is disallowed and returns an appropriate security-related error to the calling code.

- (void)connection:(NSURLConnection *)connection
willSendRequestForAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge
{
    if (self.authenticationChallenge) {
        self.authenticationChallenge(connection, challenge);
        return;
    }
    
    if ([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]) {
#warning hack
      if ([self evaluateServerTrust:challenge.protectionSpace.serverTrust forDomain:challenge.protectionSpace.host]) {
        NSURLCredential *credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];
        [[challenge sender] useCredential:credential forAuthenticationChallenge:challenge];
      } else {
        [[challenge sender] cancelAuthenticationChallenge:challenge];
      }
      return;
#warning end hack

**Comment by segiddins** [comment]
Again, this is _not_ an issue in RestKit -- you should put in a PR to AFNetworking to fix the issue.
