### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by NikZar** [RestKit/RestKit#2221]
Hi all, since I have upgraded to the latest version of cocoapods, I am not able to compile my project.
Here it follows a screenshot of the corresponding error:

![screen shot 2015-05-17 at 23 44 53](https://cloud.githubusercontent.com/assets/1833749/7672323/ceed5bac-fcee-11e4-9ab1-25f131e3f0f1.png)

Any suggestion on how to solve this issue?

I have already tried by deleting Pods.lock and Pods folder, and running 'pod repo remove master' and 'pod setup' before 'pod install'.

Here it follows my Podfile content:

source 'https://github.com/CocoaPods/Specs.git'

pod 'RestKit', '~> 0.20.0'
pod "AMSlideMenu", "~> 1.5.3"
pod 'FBSDKCoreKit'
pod "youtube-ios-player-helper", "~> 0.1.1"

**Comment by segiddins** [comment]
RestKit does not yet support building as a framework, there's an open PR in progress to add that support.

**Comment by NikZar** [comment]
Should I downgrade cocoapods or is there a way to specify not to build it as a framework?
