### ISSUE TITLE
Dead readme links

### ISSUE THREAD

**Issue by thomassnielsen** [RestKit/RestKit#2228]
A bunch of links in readme.md are dead. Seems like all of the ones referring to http://restkit.org/* redirects back to GitHub (https://github.com/RestKit/RestKit). I can't find any API docs, which should theoretically live on http://restkit.org/api/latest, but that also redirects back to GitHub.

**Comment by segiddins** [comment]
Yup, the website is down. Feel free to check the docs on cocoadocs.org, though!

**Comment by mozeryansky** [comment]
Will the website be back up or should the links be redirected to cocoadocs?

**Comment by segiddins** [comment]
If appreciate a PR redirecting them!

-Samuel E. Giddins

On Jun 7, 2015, at 8:32 PM, mozeryansky <notifications@github.com> wrote:

Will the website be back up or should the links be redirected to cocoadocs?

**Comment by mozeryansky** [comment]
Looking around, I see that links to classes won't work. I even found a comment you made on appledocs git issues referencing this: https://github.com/CocoaPods/cocoadocs.org/issues/136.

I'll look through the code/wiki to see if there are any links that can be fixed.

So will the site ever be back up, or should the future work not consider the website other then to redirect to the git repo?

**Comment by mozeryansky** [comment]
I made a pull request for some broken links which could be fixed: https://github.com/RestKit/RestKit/pull/2230

If you would like to continue the conversation there, I'm willing to help out.
(I'm doing this because I thought RestKit was dead at first due to a lot of links being broken; however, the project is very much still alive.)
