### ISSUE TITLE
Swift 2.0 RestKit forcing HTTPS (w/ allowInvalidSSLCertificates = true)

### ISSUE THREAD

**Issue by jwardle** [RestKit/RestKit#2234]
Hi, not sure if this is really a RestKit issue - or changes in the Swift 2.0 APIs that stops the intended RestKit functionality from working - but logging it for awareness. 

When calling a URL beginning with http:// and allowInvalidSSLCertificates = true (there isn't an SSL certificate on the endpoint anyways...) then I receive the following error:
```
App[39045:10528426] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9847)
App[39045:10528267] E restkit.network:RKObjectRequestOperation.m:174 POST 'http://localhost:8080/api/oauth/token' (0) [0.0005 s]:
error=Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo=0x7f9fb2eb9cf0 {_kCFStreamErrorCodeKey=-9847, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x7f9fb5437cc0 "An SSL error has occurred and a secure connection to the server cannot be made.", NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://localhost:8080/api/oauth/token, NSErrorFailingURLStringKey=https://localhost:8080/api/oauth/token, _kCFStreamErrorDomainKey=3}
```
As you can see from the first Log line the URL is clearly HTTP and not HTTPS, however the error received is stating the HTTPS based URL failed. Somehow the URL is being changed, however cannot see where this is occurring by stepping through code. 

Using RestKit 24.1 with AFOAuth2Client 1.0. Before updating to Swift 2.0 (from 1.1) this functionality worked fine without error. Given the abstraction RestKit provides between my code and underlying NSURLSession/NSURLConnection I'm struggling to see how I can change this behaviour.

**Comment by wainglaister** [comment]
It's because you're using iOS 9, transport security is changing the URL as HTTP is no longer acceptable. It has nothing to do with RestKit or AFNetworking directly.

**Comment by jwardle** [comment]
Just found this after posting the above. Apologies!

http://stackoverflow.com/questions/30816623/xcode-7-and-swift-2-0-command-failed-due-to-signal-abort-trap-6
