### ISSUE TITLE
RestKit does not build on iOS < 7.0

### ISSUE THREAD

**Issue by emlynmac** [RestKit/RestKit#2237]
Although the pod spec suggests that restKit can be used from iOS 5.1.1, the use of NS_DESIGNATED_INITIALIZER in the RKManagedObjectStore.m file causes the compile to fail on Xcode 5 / iOS 6 target.

I have a workaround in place to #define this if it is not, but an upstream fix is the proper fix.

Thanks,

**Comment by segiddins** [comment]
@emlynmac please send in a PR with a fix!

**Comment by cryptojuice** [comment]
This should fix #2301
