### ISSUE TITLE
IBInjection error

### ISSUE THREAD

**Issue by fbartolom** [RestKit/RestKit#2244]
I followed your instructions as well as many other tutorials, but I keep getting:
IDEBundleInjection.c: Error 3587 loading bundle '/Users/fbartolom/Library/Developer/Xcode/DerivedData/inArrivoHD-ebjdiuuwdpdvchgmpsyqkpvvvyhw/Build/Products/Debug-iphonesimulator/inArrivoHD Tests.xctest': The bundle “inArrivoHD Tests” couldn’t be loaded because it is damaged or missing necessary resources.

And no solution in view.

**Comment by segiddins** [comment]
This looks like a project setup issue rather than a restkit issue.
