### ISSUE TITLE
Compiler Error XCode 6.4

### ISSUE THREAD

**Issue by joaomvfsantos** [RestKit/RestKit#2251]
Just created a clean project in XCode 6.4 and added RestKit as a cocoa pod. I am getting the following errors when compiling lcl_RK.h and lcl_config_components_RK.h files.

![restkit error 1](https://cloud.githubusercontent.com/assets/2461538/8871483/85fba53c-31ed-11e5-8d32-3ece6e2ee318.png)
![restkit error 2](https://cloud.githubusercontent.com/assets/2461538/8871484/861dc806-31ed-11e5-85f2-5ed25304d1fb.png)

Any views on how to solve this? Thanks in advance.

**Comment by david-spaeth** [comment]
Hi,

I had the same problem.Resolved after using cocoapods version 0.38.0. 

it's cocoapods 0.38.1 that generates this compilation error

**Comment by joaomvfsantos** [comment]
Perfect. Thank you!
