### ISSUE TITLE
Issue with Cocoapods version 0.38.1

### ISSUE THREAD

**Issue by RomainBoulay** [RestKit/RestKit#2252]
Hey,

Since the last version of Cocoapods, the [0.38.1](https://github.com/CocoaPods/CocoaPods/releases/tag/0.38.1), we're having compilation errors:

(...)/Pods/RestKit/Code/ObjectMapping/RKHTTPUtilities.h:32:5: note: candidate found by name lookup is 'RKRequestMethod::RKRequestMethodPOST'
    RKRequestMethodPOST         = 1 << 1,

Any idea how to fix this?

Thanks!

**Comment by yoman07** [comment]
I have the same problem.

**Comment by sguillope** [comment]
Try with 0.38.2 just released today

**Comment by segiddins** [comment]
Yeah, this is a CocoaPods issue that should've been fixed with 0.38.2.
