### ISSUE TITLE
AFNetworking dependency is (too) old (really)

### ISSUE THREAD

**Issue by jcayzac** [RestKit/RestKit#2266]
Hi,

Do you plan to eventually update the dependency on AFNetworking? You currently depend on `1.3` but the latest is `2.5`.

**Comment by segiddins** [comment]
There are already several open issues on the matter, but my desire would be to drop the AFNetworking dependency eventually, but seeing as I no longer use RestKit at work, I've been unable to devote the necessary time.

**Comment by jcayzac** [comment]
Thanks for the quick answer, and sorry if that was a duplicate ([I did a search, but it didn't return anything](https://github.com/RestKit/RestKit/issues?utf8=%E2%9C%93&q=AFNetworking+in%3Atitle+is%3Aissue+is%3Aopen+))

**Comment by wainglaister** [comment]
Still work in progress, but check out https://github.com/oligriffiths/RestKit

**Comment by jcayzac** [comment]
@wainglaister nice
