### ISSUE TITLE
Multithreading_Violation_AllThatIsLeftToUsIsHonor when using named routes.

### ISSUE THREAD

**Issue by itsSaad** [RestKit/RestKit#2269]
i have this line for setting up named route.

        [router.routeSet addRoute:[RKRoute routeWithName:@"match_contacts" pathPattern:@"/users/:userId/match_contacts" method:RKRequestMethodPOST]];

when RK goes find the value of :userId it doesn't use the correct managedObjectContext because im sending this request on as async on a different thread then the Main one.

I have CoreDataConcurrency Debugging on which throws an exception when RK want to get the value of :userId in the pathPattern for the set Route.

Any way around this. or has this been fixed in a newer version.
im using Restkit 0.24.1

Here is the Stack: 
![screenshot 2015-08-16 02 10 26](https://cloud.githubusercontent.com/assets/4000342/9290862/1a6d5104-43bc-11e5-834b-62482ea6812c.png)

Here is the actual line from RestKit:
![screenshot 2015-08-16 02 11 41](https://cloud.githubusercontent.com/assets/4000342/9290867/3b56f960-43bc-11e5-88b8-d3bc8553ae87.png)

**Comment by segiddins** [comment]
@itsSaad hm, a PR with a fix for this would be excellent!

**Comment by itsSaad** [comment]
@segiddins do you think this is a valid bug?

**Comment by segiddins** [comment]
yeah, we shouldn't be causing any concurrency exceptions

**Comment by itsSaad** [comment]
I was able to get it moving from that exception with the following:

    for (SOCParameter* parameter in _parameters)
       {
           NSManagedObject *mObject = (NSManagedObject *) object;
           NSManagedObjectContext *context = mObject.managedObjectContext;
          __block NSString *token;
          [context performBlockAndWait:^{
              token = [NSString stringWithFormat:@"%@", [object valueForKey:parameter.string]];
          }];
          NSString* stringValue = token;
            if (nil != block) {
          stringValue = block(stringValue);
        }
        if (nil != stringValue) {
          [parameterValues setObject:stringValue forKey:parameter.string];
        }
      }

and also had to #import "CoreData.h" in SOCKit.m

**Comment by itsSaad** [comment]
@segiddins  can you comment on the approach i used. or there should be a more elegant way?

**Comment by segiddins** [comment]
SOCKit itself should know nothing about CoreData, I'm guessing the change should be in the object manager, if the passed object is a managed object and if so, doing performBlock

**Comment by itsSaad** [comment]
yes thats what i figured. but getting the value is SOCKit's work. no?

**Comment by segiddins** [comment]
yeah, but SOCKit is a separate library, it knows absolutely nothing about CoreData

**Comment by segiddins** [comment]
Actually, reading through the relevant code, I'm going to say that this is user error -- you'll need to do your own `performBlock` before calling `getObjects`

**Comment by itsSaad** [comment]
Ok. so we would be doing the parsing of the value in RKPathMatcher instead of SOCKit if its a managedObject.

**Comment by segiddins** [comment]
No, I'm pretty sure you just need to wrap your `getObejcts` call in a `performBlock` in your own code.

**Comment by itsSaad** [comment]
ok. let me try it then.
