### ISSUE TITLE
Cancel a specific request

### ISSUE THREAD

**Issue by KyleXie** [RestKit/RestKit#2270]
I see we have cancelAllObjectRequestOperationsWithMethod, we can use it to cancel requests, but what if I just want to cancel one specific request, not all requests with a same URL patten?  Some thing like the NSURLSessionDataTask, we can use it to cancel the request?

**Comment by mkral** [comment]
Keep track of each RKObjectRequestOperation and use -(void)cancel on the operation. That's all cancelAllObjectRequestOperationsWithMethod is doing
