### ISSUE TITLE
Fix imports in public header files

### ISSUE THREAD

**Issue by 0xced** [RestKit/RestKit#2288]
Imports in public header files should be `#import <RestKit/Subdirectory/RKHeader.h>` instead of `#import "RKHeader.h"`

This is required for RestKit to be compatible with future CocoaPods version because of CocoaPods/CocoaPods#4057 (The `HEADER_SEARCH_PATHS` will no longer be constructed recursively) introduced in 0.39.0.beta.1.

**Comment by segiddins** [comment]
@0xced I'm not seeing any issues building with CocoaPods master?

**Comment by 0xced** [comment]
I haven’t tried with master but I can reproduce this issue with version 0.39.0.beta.3, here is how:

1. Create a new iOS application (Single View Application, Objective-C)
2. Run `pod init`
3. Add `pod 'RestKit'` in the app target of the Podfile
4. Run `pod install`
5. Add `#import <RestKit/RestKit.h>` at the top AppDelegate.m

The project wont compile because `'RKObjectMapping.h' file not found`
```
In file included from /Users/0xced/Desktop/Demo/Demo/AppDelegate.m:11:
In file included from /Users/0xced/Desktop/Demo/Pods/Headers/Public/RestKit/RestKit.h:25:
/Users/0xced/Desktop/Demo/Pods/Headers/Public/RestKit/ObjectMapping.h:23:9: fatal error: 'RKObjectMapping.h' file not found
#import "RKObjectMapping.h"
        ^
1 error generated.
```

**Comment by hieuld** [comment]
@Oxced: How did you solve it? Any workaround? Thanks.

**Comment by xjf1990930** [comment]
you can try :
And the following linker flags must be set:

    -ObjC
    -all_load

**Comment by hieuld** [comment]
It doesn't help

**Comment by yaalaa** [comment]
it'd nice to get it fixed, folks

**Comment by wlue** [comment]
+1, having this issue as well

**Comment by horseshoe7** [comment]
same here

**Comment by fabioprodoctor** [comment]
same here

**Comment by zerodiff** [comment]
I got around this by adding these to the *User Header Search Path* in the Xcode project *Build Settings*:

 $(PROJECT_DIR)/Pods/Headers/Public/RestKit
 $(PROJECT_DIR)/Pods/RestKit/Vendor

It's not elegant, but it's a work-around.

**Comment by horseshoe7** [comment]
That worked, but then other pods weren’t being found.

I just inherited this project.  First day on a new job.  Codebase looks messy.

I’ve tried rebuilding everything.  Even killing the .xcworkspace and Pods, and rebuilding all of that.  It just gets worse for RestKit after that.  Duplicate Symbols and so on.

**Comment by segiddins** [comment]
This is a known issue with a fix in progress, more comments won't get a fix released faster.

**Comment by horseshoe7** [comment]
That’s fine.  Was just providing more info.    

Workarounds are appreciated.

**Comment by horseshoe7** [comment]
I'm not sure if what I was seeing was a RestKit related issue at all.   I solved the problem with the solution presented here:  http://stackoverflow.com/a/16560290/421797

**Comment by wekancodemohammed** [comment]
Didn't worked any options above.. Anyone can help me with the solution...Please

**Comment by rohitsyscraft** [comment]
same here, pls help me
