### ISSUE TITLE
Can I use RestKit in my iOS9 app? 

### ISSUE THREAD

**Issue by rameshal** [RestKit/RestKit#2294]
I have been using RestKit in my app so far with no issues. Can I continue using RestKit in my app if I build it for iOS9?. The reason I have this doubt is because NSURLConnection has been deprecated in iOS9, but it is used in AFNetworking 1.3.4 (RestKit uses AFNetworking 1.3.4).

**Comment by segiddins** [comment]
Yes, you can. IN the future, please ask questions such as these elsewhere. Issues are for reporting bugs in RestKit itself.
