### ISSUE TITLE
NSManagedObjectContext cannot refresh objects in other contexts

### ISSUE THREAD

**Issue by dev4dev** [RestKit/RestKit#2295]
I have such error in file `RKManagedObjectRequestOperation.m` on line `826`
It appears when I send __DELETE__ request using fetched object from `NSManagedObjectContext` created via  

 `[[RKObjectManager sharedManager].managedObjectStore newChildManagedObjectContextWithConcurrencyType:NSMainQueueConcurrencyType tracksChanges:YES];`

If I use just `mainQueueManagedObjectContext` everything is okay.
Maybe `self.managedObjectContext` in `RKManagedObjectRequestOperation.m` should be obtained from `self.targetObject` ? Or I'm doing something wrong with it?

**Comment by adly-holler** [comment]
`self.targetObject`, if present, must belong to `self.managedObjectContext`. We can't obtain `managedObjectContext` from `targetObject` because `targetObject` is optional.

**Comment by dev4dev** [comment]
hah, sorry, I'd opened GitHub before I used my brain
