### ISSUE TITLE
tvos support

### ISSUE THREAD

**Issue by RyanCodes** [RestKit/RestKit#2297]
Utilizing the Cocoapods tvos branch I can not use my private pod which is dependant on RestKit since RestKit 0.25.0 does not support platform :tvos 

Please make this so :)

**Comment by segiddins** [comment]
@RyanCodes please make a PR ;)
But first, all of restkits dependencies will need to add tvos support.

**Comment by maremmle** [comment]
I am just wondering … how should RestKit ever be able to support tvOS if it needs all dependencies to support tvOS first and ist still based on AFNetworking 1.3. ?

**Comment by RyanCodes** [comment]
we chose other options for tvOS

**Comment by maremmle** [comment]
@RyanCodes ok what do I need to do to port my existing RestKit stack?

**Comment by taradayka** [comment]
hi, you can use this https://github.com/taradayka/RestKit-tvOS-
