### ISSUE TITLE
RestKit fails to build when a podfile also contains CocoaLumberjack as a dependency

### ISSUE THREAD

**Issue by baumatron** [RestKit/RestKit#2300]
When a project includes both RestKit and CocoaLumberjack as a dependency using CocoaPods, the RestKit Pod target fails to build.

`Undefined symbols for architecture arm64:`
  `"_OBJC_CLASS_$_DDLog", referenced from:`
      `objc-class-ref in RKLumberjackLogger.o`
`ld: symbol(s) not found for architecture arm64`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

The reason for this is that support for CocoaLumberjack logging is compiled conditionally based on the availability of DDLog.h in the include path. The header file is there because the framework consuming project's podfile requires CocoaLumberjack, but the RestKit pod does not link to CocoaLumberjack.

**Comment by segiddins** [comment]
Is this building restkit as a framework?

**Comment by enell** [comment]
Yes. I get the same and only when building as a framework

**Comment by segiddins** [comment]
Probably will be fixed by making a proper cocoalumberjack subspec

**Comment by segiddins** [comment]
This has been fixed as of 0.26.
