### ISSUE TITLE
RKObjectMapping.h Not Found

### ISSUE THREAD

**Issue by hieuld** [RestKit/RestKit#2302]
I "pod update", and my RestKit version now is 0.25.0, my RKValueTransformers is 1.1.2, and an error appeared "RKObjectMapping.h" not found.

What did RestKit change in the new version, that I check on the its github cannot find anything.

Note: I am using XCode7-beta5, objective-c

**Comment by segiddins** [comment]
This looks like a duplicate of #2288

**Comment by hieuld** [comment]
So, how can I fix it? @segiddins ?

**Comment by segiddins** [comment]
Make a pull request? I'm without a laptop now so I can check anything in Xcode.

**Comment by hieuld** [comment]
I am quite new to github system. How can I make a pull request?

**Comment by hieuld** [comment]
The thing is even I use the older version of RestKit (e.g., 0.23.1), the issue is still there.

**Comment by minaskamel** [comment]
Downgrade Cococapods to 0.38.0 solved the issue for me.
