### ISSUE TITLE
RKManagedObjectRequestOperation fails obtaining permanent ID for inserted objects or save context

### ISSUE THREAD

**Issue by choofie** [RestKit/RestKit#2307]
Can anybody confirm that the following line in RKManagedObjectRequestOperation works fine and returns YES under iOS 9 ?
```
_blockSuccess = [self.privateContext obtainPermanentIDsForObjects:insertedObjects error:nil];
```
In my (plain Objective-C) app I'm using RestKit from the beginning, and it worked like charm until I've installed the app on any iOS 9 device.
It seems that it is able to download the content (JSON) but fails under the CoreData saving process.

I've also tried to update the RestKit to the latest version (0.25)  - so the error: parameter will be ```&localError``` -, but it not just returns NO, it also crashes with EXC_BAD_ACCESS on that line.

Note that the same code with the same content works fine on any iOS 8 device, so after the step:
```
_blockSuccess = [self.privateContext obtainPermanentIDsForObjects:insertedObjects error:nil];
```
the ```_blockSuccess = YES```, and continues successfully.
But on iOS 9 after the following step:
```
_blockSuccess = [self.privateContext obtainPermanentIDsForObjects:insertedObjects error:nil];
```
the ```_blockSuccess = NO```, and crashes badly!

**Comment by segiddins** [comment]
Could you look into submitting a patch with a test that exposes the issue, and ideally a fix? Thanks!

**Comment by choofie** [comment]
I'm trying to workaround this for days, but with no luck.
Does anyone experiencing similar issues after transferring to iOS 9 ?
Any help would be appreciated!

**Comment by choofie** [comment]
Okay, finally I've found a workaround for this issue!
But first, I want share the mysterious behaviour, that lead me to the right workaround.

**BUG - LONG DESCRIPTION:**
In my project the CoreData was set to use the *DataModel 2* version for a long time. Now - only for testing purpose - I created the next version (3) based on the last one without any changes, using **Xcode 7**. So I've changed the Model to use the "new" version and gave another try to *build and run*. 
**SURPRISE** for the first time the RestKit was able to map everything properly under iOS 9!!! 
But this wasn't enought... After this successful scenario I made another *run* and everything just worked badly again. **UNTIL** I set the DataModel version back to 2. 
**ANOTHER** successful scenario on *iOS 9*, *BUT* fails again when I *run* it again without any changes.

*NOTE: Once again, the DataModel 2 and DataModel 3 are equivalent -> so no migration needed!*

**BUG - SHORT DESCRIPTION:**
- Right after I change the ModelVersion from 2->3 or 3->2 the RestKit worked fine.
- After a clean install it wasn't able to perform successful entity map.
- It doesn't work also after any successful scenario, until I change the ModelVersion version number.

**THE POINT:**
After I've spent hours on the right way of CoreData database creation and proper model setup while inspecting the code, I double checked the file system once again. It seems the ```"db.sqlite-wal"``` one of the generated file becomes **Zero bytes** on every failing scenario.

The first Google hit offered me a possible workaround for similar issue happens during **CoreData migration**:
http://pablin.org/2013/05/24/problems-with-core-data-migration-manager-and-journal-mode-wal/

**ALMOST THERE:**
However I wasn't satisfied, because I knew that my database didn't change so I shouldn't be a migration issue, but I gave a try for this workaround to let see what the debugger says.
As expected, the isModelCompatible got true this time as well, so it doesn't proceed into the migration phase, but let's release the debugger to continue the application processes. AND THEN OMG, IT WORKS! Let's try another run: STILL WORKS!!! But wh? ho? wh? what happened? 

It is a workaround for CoreData migration bug happened two years ago. So the only change in the code was to set the ```NSSQLitePragmasOption: @{@"journal_mode": @"WAL"}``` for a value that used to be the same by default. And I found the verification on this.

**GOT IT:**
Here's the same problem happened with someone else:
http://stackoverflow.com/questions/32629302/nspersistentstorecoordinator-addpersistentstorewithtype-method-error-without-jo

**CONCLUSION:**
If anyone is expecting the same issue (even without any informative error as in my case) just check the ```journal_mode``` is set properly for the persistent coordinator, and make sure you also have the workaround for migration if necessary!

**Comment by ILI4S** [comment]
@choofie can you please clarify what you did to fix the crash? you added `NSSQLitePragmasOption: @{@"journal_mode": @"WAL"}` to the NSPersistentStore initialization options?

**Comment by MateLorincz** [comment]
@ILI4S Exactly. The only change was when I set up the `NSPersistentStoreCoordinator` I had to explicitly include `@{@"journal_mode": @"WAL"}` in its options. Just like here in this post: http://pablin.org/2013/05/24/problems-with-core-data-migration-manager-and-journal-mode-wal/

You should also check the CoreData created `db.sqlite-wal` file in `{generated application folder}/Documents` folder. This temporary file should not be empty if you successfully set up you CoreData database. 

_In my case the `db.sqlite-wal` file's size was Zero byte, but when I add the `journal_mode` `WAL` to the options for the persistent store coordinator it started working._

**Comment by ILI4S** [comment]
Thanks for your response @MateLorincz. I'm not sure whether I'm encountering the same issue as you or not, I'm trying to debug an instance of #2418 but without the ability to reproduce it myself :( I just get crash reports from my testers.

The blog post you linked actually suggests setting "journal_mode" to "DELETE" to workaround the migration issue (same with the stackoverflow link you posted). That's why I am confused that setting "journal_mode" to "WAL" worked for you -- [it seems like thats the default since iOS 7](http://stackoverflow.com/questions/18870387/core-data-and-ios-7-different-behavior-of-persistent-store) so you shouldn't have to specify it at all. 

In our case, I am still getting crash reports on `obtainPermanentIDsForObjects:error:` after adding `@{@"journal_mode": @"WAL"}` to the persistent store initialization options. So I'm trying `@{@"journal_mode": @"DELETE"}` next. Not sure whether the workaround in the blog post of setting "WAL", then (if there is a migration pending) setting "DELETE", then setting "WAL" again is necessary.

**Comment by choofie** [comment]
@ILI4S I've just double checked the regarding commit in history (_sorry it was a year ago and I didn't remember it correctly)_. So I'm going to answer you again. :)

Basically I pasted Pablin's **Core Data workaround setup** into my code as is to configure the `(NSPersistentStoreCoordinator *)persistentStoreCoordinator` and it works like charm.

You know right: the default `journal_mode` is `WAL`, so you don't need to set it explicitly until you set this option to another value before `(eg. `@{@"journal_mode": @"DELETE"}`)`.

If you also need to perform a migration, then I'd suggest to check out Pablin's workaround and see what is your and your QA experience with that.

You should also check the size/content of `db.sqlite-wal` when you got crash on line `obtainPermanentIDsForObjects:error:` to make sure we're having the same issue.

**Comment by ILI4S** [comment]
@choofie thanks for clarifying!

Unfortunately, in my case, I haven't been able to reproduce the issue on demand :( it's only remote beta testers that are encountering the issue, so I can't check the size/content of db.sqlite-wal at the moment. I'm hoping that setting "journal_mode" to "DELETE" is sufficient--maybe the "workaround" solution of setting "WAL" and then "DELETE" and then "WAL" again isn't necessary. I suppose one drawback of "DELETE" vs "WAL" is the migration may take longer.
