### ISSUE TITLE
Using RestKit as a git submodule

### ISSUE THREAD

**Issue by andrey-krukovskiy** [RestKit/RestKit#2309]
From v0.25.0 I cannot use RestKit as a git submodule.
The same issue described here http://stackoverflow.com/questions/31901347/restkit-giving-error-after-installation-as-a-git-submodule

**Comment by segiddins** [comment]
it should work if you run `pod install` in the RestKit directory first -- as of 0.25, the only supported method of installation is CocoaPods, as I don't have the time to maintain multiple supported installation methods.

**Comment by andrey-krukovskiy** [comment]
After running ```pod install``` in the RestKit directory I get message ```can't locate file for: -lPods-RestKit```
What can I do with it?

**Comment by segiddins** [comment]
Not quite sure what's going wrong, you'll have to debug it manually, sorry.

**Comment by lrh198681** [comment]
@andrey-krukovskiy @segiddins have you resolved the problem?

**Comment by andrey-krukovskiy** [comment]
@lrh198681 No, I'm not familiar with cocoa pods, so I just use old version of RestKit linked via submodules. I didn't have time to figure it out.
