### ISSUE TITLE
Version 0.25.0 updates dropped the support for git submodules?

### ISSUE THREAD

**Issue by rpranata** [RestKit/RestKit#2314]
I noticed that version 0.25.0 that has been released recently dropped support for using restkit as submodules? We are not using Pod for the time being, is there another way to update restkit without using Pod?

**Comment by segiddins** [comment]
You can hack something together, but I no longer have the bandwidth to officially support multiple installation methods.

**Comment by ILI4S** [comment]
:cry: 

```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

RIP RestKit

**Comment by segiddins** [comment]
You'll have to run `pod install`

**Comment by ILI4S** [comment]
@segiddins I appreciate the fact that you may be overwhelmed but I really have to question the decision to __require__ CocoaPods. There are many good reason to __not__ use CocoaPods and the very least that you can do is to provide release notes indicating that RestKit now _requires_ CocoaPods. I'm unable to find the release notes for 0.25.0 on github: https://github.com/RestKit/RestKit/releases

I also hope that you reconsider your decision but wish you the best of luck in managing this project.

**Comment by segiddins** [comment]
I haven't had time to write up release notes. I'd be more than happy to accept a PR supporting other methods of installation, but so far I haven't received any.

**Comment by revolter** [comment]
@segiddins, I did run `pod install` but I get the same error as @ILI4S.
