### ISSUE TITLE
Restkit hangs UI even if called from another thread

### ISSUE THREAD

**Issue by itsSaad** [RestKit/RestKit#2322]
RKObjectManager *manager = [RKObjectManager sharedManager];
        NSString *path = [NSString stringWithFormat:@"users/%@/match_contacts", currentUser.userId];
    
        RKManagedObjectRequestOperation * request = [manager appropriateObjectRequestOperationWithObject:currentUser method:RKRequestMethodGET path:path parameters:@{USER_TOKEN: currentUser.userToken}];
    
        [request setSavesToPersistentStore:YES];
        [request setTargetObject:nil];
        request.deletesOrphanedObjects = NO;
    
        [request setCompletionBlockWithSuccess:^(RKObjectRequestOperation *operation, RKMappingResult *mappingResult)
         {
             NSLog(@"Got Matched Contacts");
             NSArray *contacts = [mappingResult array];
             successBlock(contacts);
         } failure:^(RKObjectRequestOperation *operation, NSError *error)
         {
             NSLog(@"Request Failed. Error: [%@].", error);
             failureBlock(error);
         }];
    
        [manager enqueueObjectRequestOperation:request];

I have the following code. it seems that the api call returns a success (200). but somewhere when restkit starts to map the response, it just hangs and my success or failure blocks are not called.

This issues is hard to understand as it appears sometimes and other times the blocks are called fine and doest hang the ui. all this code im doing in the new background thread.
Any ideas?

**Comment by segiddins** [comment]
What queue does your currentUser belong to?

**Comment by itsSaad** [comment]
you mean the `NSManagedObjectContext`?

**Comment by itsSaad** [comment]
ok it seems that i had an entity relationship which had no inverse relationship set. now that i have setup a reverse relationship. this problem doesn't seem to appear. but is there a known behavior of mapping from json when no inverse relationship is found for the object being mapped?
