### ISSUE TITLE
- `AFNetworking (= 2.6.0)` required by `Podfile.lock` - `AFNetworking (~> 1.3.0)` required by `RestKit/Network (0.25.0)`

### ISSUE THREAD

**Issue by onlyver** [RestKit/RestKit#2328]

**Comment by onlyver** [comment]
why it can't support de newest AFNetworking,can you update it as soon  as possible

**Comment by segiddins** [comment]
There are a bunch of open issues about this already, and this is a super unfriendly way to ask me to spend tens of hours of my time for free on a library I no longer personally use.

**Comment by onlyver** [comment]
sorry ,I have never publish issue on the github ,I just make a try so sorry,so you are too busy to spend your time to solve it issue right?
