### ISSUE TITLE
Support for watchOS2

### ISSUE THREAD

**Issue by neobeppe** [RestKit/RestKit#2329]
Please, add watchOS support for RestKit installed via CocoaPods

**Comment by segiddins** [comment]
We first need an AFNetworking 1.3.x release that supports it.

**Comment by neobeppe** [comment]
The latest 1.3.x AFNetworking release was in April 2014 (https://github.com/AFNetworking/AFNetworking/releases/tag/1.3.4)

**Comment by segiddins** [comment]
I know.
