### ISSUE TITLE
RestKit is unable to find CoreData defines when using CocoaPods

### ISSUE THREAD

**Issue by mdonati** [RestKit/RestKit#2335]
I'm unable to compile my code because RestKit can't find the _COREDATADEFINES_H define. I made sure that CoreData is added as framework, imported to the prefix header file and also that it comes before the RestKit import.
I'm using CocoaPods 0.38.2, but also tried with 0.39 and 0.38 and also 0.37.2. No matter the version I used, I always got the same error. As for RestKit, I'm using 0.23.1.
It was working fine until I made a pod install to include JTSlideShadowAnimation pod. The weird thing is that it installed all the pods again, regardless they were all installed already (except of course the new one I wanted to add).
I really don't know what else to do. I double and tripled checked header search path, framework search path and other linker flags and everything seem setup as expected.

**Comment by segiddins** [comment]
Can you see if this is fixed with 0.25?

**Comment by mdonati** [comment]
You saved my day! Thank you very much.
