### ISSUE TITLE
Spam on wiki pages. 

### ISSUE THREAD

**Issue by kojustin** [RestKit/RestKit#2349]
The wiki for this project has a bunch of spam pages on it. :(

![screen shot 2015-11-10 at 2 15 39 pm](https://cloud.githubusercontent.com/assets/965243/11077549/8aa86138-87b5-11e5-889c-a5456d5445c9.png)

**Comment by segiddins** [comment]
Thanks, I just restricted editing and deleted the spam pages. Very disappointed that this was necessary :(
