### ISSUE TITLE
0.26 problems with CoreData headers imports

### ISSUE THREAD

**Issue by dev4dev** [RestKit/RestKit#2352]
There are a lot of broken statements like this

`#if __has_include("RKCoreData.h")`

which should be replaces with 

`#if __has_include(<RestKit/CoreData.h>)`

**Comment by dev4dev** [comment]
the same thing with 

```
#elif __has_include(<RestKit/CocoaLumberjack/RKLumberjackLogger.h>)
  #import <RestKit/CocoaLumberjack/RKLumberjackLogger.h>
  #define RKLOG_CLASS RKLumberjackLogger
```

**Comment by segiddins** [comment]
Can you open up a PR fixing things? I didn't have any issues importing RestKit during development.

**Comment by skydivedan** [comment]
nice catch. looking forward to 0.26.1!

**Comment by rpranata** [comment]
Can we please have a patch for this one in CocoaPods? It does not compile at the moment with the current v0.26.0 release.
