### ISSUE TITLE
RestKit doesnt build in version 0.26

### ISSUE THREAD

**Issue by mcfedr** [RestKit/RestKit#2356]
Maybe this is my problem, as I would assume its working for some people.

I have updated to 0.26 today, I am using `use_frameworks!` in my Podfile (cocoapods 0.39)

It fails in `CoreData.h` on `#import <RestKit/CoreData/RKEntityMapping.h>` with file not found

I have tried cleaning, removing `Pods/`, no luck getting this to build.

**Comment by segiddins** [comment]
Can you try the current development branch?

**Comment by MarcoBrescianini** [comment]
Same for me

**Comment by frane** [comment]
Same here. Seems to be related to CocoaPods 0.39. 
Older versions of CocoaPods (```pod _0.38.2_ install```) work fine.

**Comment by mcfedr** [comment]
@segiddins I tried installing from development (`pod 'RestKit', :git => 'https://github.com/RestKit/RestKit.git', :branch => 'development'`), same problem

    .../Pods/RestKit/Code/CoreData.h:22:9: 'RestKit/CoreData/RKEntityMapping.h' file not found

@frane I was having problems with everything with CocoaPods 0.39 until I started using `use_frameworks!`, now I have a problem again, but only with RestKit 0.26

**Comment by frane** [comment]
@mcfedr I'm not using ```use_frameworks!```, but when I tried, I had the same experience as you did.

**Comment by MarcoBrescianini** [comment]
Me too. 
@mcfedr I managed to fix the problem removing ```use_frameworks!``` flag from podfile

**Comment by mcfedr** [comment]
@MarcoBrescianini fun! so version 0.26 seems to break `use_frameworks!` but also fix when its not there, version 0.25 doesn't work without `use_frameworks!`

**Comment by mcfedr** [comment]
Ah, well, I take that back slight, the development version works without `use_framework!` but 0.26 doesnt.

**Comment by segiddins** [comment]
If development works, I'll release a new patch version. If not, please share a project I can use to debug or submit a PR with a fix. Thanks!

**Comment by mcfedr** [comment]
I'm not really sure where to start with a pull request, but I have made a project that shows this bug 
https://github.com/mcfedr/TestRestKit

**Comment by timbodeit** [comment]
RestKit 0.26.0 doesn't work with CocoaPods 0.39.0, because it does not include [CocoaPods#4267](https://github.com/CocoaPods/CocoaPods/pull/4267).

The changes made in #2310 assume, that the paths in the header_mappings_dir are preserved.
Cocoapods 0.39.0 does not do that and places the header at `RestKit/RKEntityMapping.h` instead of `RestKit/CoreData/RKEntityMapping.h`.

When using the current CocoaPods master, there are three different issues however:

1. lcl_RK.h file not found. See #2360
- `_SYSTEMCONFIGURATION_H` not defined in `AFHTTPClient.h`  
  Same issue exists with RestKit 0.25.0. Bisected this down to [CocoaPods#4267](https://github.com/CocoaPods/CocoaPods/pull/4267) as well.
  Not sure what exactly the reason for this is, but I assume that the way headers are integrated now leads to the prefix header not being applied properly.
- For me the first build after a clean doesn't work. I have to build two times in a row, because otherwise the headers are not found. RestKit development, CocoaPods master, Xcode 7.1

When specifying `use_frameworks!` in the Podfile, I can't get RestKit development integrated without additional workarounds, regardless of CocoaPods version.

Tested with: 
Xcode `6.4`, `7.0.1` and `7.1`
CocoaPods `0.38.1`, `0.38.2`, `0.39` and `master`
https://travis-ci.org/timbodeit/RestKitTest/builds/93243450

**Comment by segiddins** [comment]
Feel free to make PRs fixing it and I'd be happy to ship a patch release.

**Comment by timbodeit** [comment]
@segiddins Could you give me some input on @2360 please?

**Comment by tengelmeier** [comment]
I'm wondering why you see the headers copied "flat" - with cocoa pods 0.39 I get the headers copied to subfolders and then compilation is broken as the sub-paths are not added to the search directory settings.   

            pod 'RestKit', '~> 0.26', :inhibit_warnings => true
 
results in a public header dir containing:

             CoreData/		
             Network/		
             ObjectMapping/		
             RestKit.h@		
             Support.h@		
             Testing.h@
             CoreData.h@		
             Network.h@		
             ObjectMapping.h@	 
             Support/		
             Testing/

**Comment by nypisces** [comment]
When will this can be fixed?

**Comment by mcfedr** [comment]
The fix for this appears to be in Cocoa Pods 1.0 beta according to https://github.com/CocoaPods/CocoaPods/pull/4267 - I haven't test it yet, but it should fix this.

**Comment by nypisces** [comment]
@mcfedr I use cocoapods 1.0.0-beta2 + ReskKit 0.26 + use_frameworks!
not work

**Comment by gunnarblom** [comment]
@jlampa @segiddins I still get missing headers in the Support folder. E.g. it says RestKit/Support/lcl_RK.h missing when referenced from RestKit/Support/lcl_RK.m.

Related? Should those be included as well in this fix?

**Comment by mcfedr** [comment]
This issue is far from closed...

I have been doing some experimenting.

First I reverted the changes to use 'framework' style headers. I cannot see the sense of this, as its trying to use the RestKit frameworks headers before the framework is built.

Using this branch gets RestKit to build and work with CocoaPods 0.39
https://github.com/RestKit/RestKit/compare/development...mcfedr:no-frameworks

Unfortunately it fails when using CocoaPods 1.0 (beta 4). But a further adjustment using relative header paths seems to solve this problem. This branch doesnt work with 0.39.
https://github.com/RestKit/RestKit/compare/development...mcfedr:relative

Furthermore the SystemConfiguration includes get all difficult with CocoaPods 1.0. Both AFNetworking and RestKit (and my project) include and link with SystemConfiguration. But for some reason when the 
AFNetworking headers are included in RestKit,, SystemConfiguration is not visible to the headers and I get build errors unless I edit AFHTTPClient and include SystemConfiguration explicitly.

So I'm not sure I have a proper solution at this point. But I feel close...

**Comment by falkobuttler** [comment]
Why is this ticket closed? This is still not working properly, even with the latest dev branch.

**Comment by mcfedr** [comment]
@falkobuttler Can you try with either of my branches, I would be really interested in what works for you, I'm trying to prepare a pull request to fix this.

**Comment by falkobuttler** [comment]
@mcfedr I tried several versions of CocoaPods and RestKit. I ended up going back to CocoaPods 0.38.1.

My scenario is that we want to enable `use_frameworks!` since we want to start using Swift pods. I could use either CocoaPods 0.38.1 or 0.39. The 1.0.0.beta.x builds are just too buggy right now.

**Comment by falkobuttler** [comment]
@mcfedr I tried your `relative` branch with both CocoaPods 0.38.1 and 0.39.0 and it didn't work - I get different kinds of `include not found` errors.

**Comment by mcfedr** [comment]
@falkobuttler the name `no_frameworks` refers to how the internal headers are found. I also use it with `use_frameworks!`. 

The `relative` branch works with 1.0 but I haven't yet managed to make a single version that works with both

**Comment by falkobuttler** [comment]
@mcfedr While I now got the no_frameworks version to compile and to use it within my application target, I can't use RestKit in any other pods.

My scenario:
- App target
- Shared library using RestKit
- RestKit a dependency of above shared library

**Comment by ezescaruli** [comment]
I agree that this issue should be re-opened, as some build errors are still happening.

@mcfedr I gave a try to your fork, at its `relative` branch on my example project:
https://github.com/ezescaruli/CocoaPodsExample/tree/mcfedr-relative
and using `CocoaPods` at its `master` branch.

I got the same as you: it works, except for `SystemConfiguration` not being found on `AFHTTPClient.h` when building the `RestKit` framework. Tried importing it on my Project prefix header, as https://github.com/AFNetworking/AFNetworking/issues/577 says, but no luck.

It's weird that `AFNetworking`'s prefix header includes it:
https://github.com/ezescaruli/CocoaPodsExample/blob/mcfedr-relative/Pods/Target%20Support%20Files/AFNetworking/AFNetworking-prefix.pch#L8
But for some reason, the `RestKit` framework is not including that header.

**Comment by horseshoe7** [comment]
Has anyone figured this out?  This is a big problem.  I have a "normal project".  Include RestKit as a dependency, try to implement RKEntityMapping as a class method in a category on a NSManagedObject subclass.  First file in the list to compile.  Fails.

**Comment by tengelmeier** [comment]
The workaround I mentioned above still woks for me. However, I don't use the frameworks variant..

**Comment by horseshoe7** [comment]
@tengelmeier your line of code: ```if target.name == "Pods-Foo" or target.name == "Pods-Bar"``` made me think it's not just a simple copy-paste solution... what should that be?

**Comment by jlampa** [comment]
https://github.com/RestKit/RestKit/pull/2397 solves this problem by changing import paths.

**Comment by falkobuttler** [comment]
@jlampa Looks like your PR got closed without being merged. Did you try using RestKit within another Pod module?

**Comment by jlampa** [comment]
No - it' still open. Though the Travis check did fail.

**Comment by doncorsean** [comment]
What's the status here? Is this resolved? I see this issue is closed although many are still reporting issues. I cannot compile using RestKit 2.6 & use_frameworks!.

Tried with Cocoapods .39 and 1.0.0.beta.5...

**Comment by waltermvp** [comment]
@mcfedr Does your workaround still work? Im having issues getting it running with the `post_install` configuration.

**Comment by waltermvp** [comment]
@mcfedr attempting to get it to run with https://github.com/RestKit/RestKit/compare/development...mcfedr:no-frameworks but have no luck. Tried both with and without the `post_install` instructions in the podfile but still no luck. am i missing something?

**Comment by mcfedr** [comment]
@waltermvp I am actually coming back to this again this afternoon, I think my 'fix' probably still has some issues.

**Comment by waltermvp** [comment]
@mcfedr thanks for the quick reply, been struggling with this the past week. My project  is now "blocked" due to this. Let me know if I can help in any way when you do work on this, thanks!

**Comment by mcfedr** [comment]
@waltermvp I am successfully building using `no-frameworks` branch using cocoapods 0.39. Using cocoapods 1-beta there are problems that are linked to AFNetworking as well.

**Comment by waltermvp** [comment]
@mcfedr let me try that again and let you know

**Comment by mcfedr** [comment]
Tell me what errors you have, I dont have any `post-install` hooks so I cannot test that.

**Comment by waltermvp** [comment]
Ok just gave it works. Had some errors but those were related to using older AFNetworking API . I commented out the offending reachability code and it compiles!! thank you very much, now all i have to do is replace the reachability code with a separate API.

**Comment by waltermvp** [comment]
@mcfedr just realized that the errors i had were caused by not having a definition for `_SYSTEMCONFIGURATION_H`. I have it imported in my PCH file and its also a linked framework for the target. Any ideas how to turn it on? FYI its a swift/obj mixed target

**Comment by mcfedr** [comment]
I have the same problems, cannot seem to find a way around it, I might also make a fork of AFNetworking 1.3 that requires SystemConfiguration.

The problem seems to be since using `use_frameworks!` each one is built separately, so it has its own PCH file, that means that when AFNetworking was built, it didn't see SystemConfiguration because it didn't require it.

This actually causes everything to fail again with Cocoapods 1, which I am hoping a patch to AFNetworking will fix.

**Comment by waltermvp** [comment]
@mcfedr  jsut found this and giving it a try.http://www.jontolof.com/cocoa/cocoapods-and-swift-compiler-warning/

Baiscally adding the imports to the bridging header. Not working at first try but ill keep hacking for a lil

**Comment by mcfedr** [comment]
I also tried added to the bridge file, didn't have any luck, as I said, I am fairly sure that each framework is being built completely by itself and so this wont help. The problem with Cocoapods 1 is that RestKit is seeing _SYSTEMCONFIGURATION_H but AFNetworking isnt so RestKit tries to use symbols that are not defined.

**Comment by waltermvp** [comment]
@mcfedr makes sense, guess the way forward is to use a separate pod for reachability

**Comment by mcfedr** [comment]
ah, wait, both RestKit and AFNetworking add `#import <SystemConfiguration/SystemConfiguration.h>` to their PCH files in the podspec.

**Comment by waltermvp** [comment]
Right so it *should* work

**Comment by mcfedr** [comment]
Fun times, the warning from both sides of the `#ifdef`

![screen shot 2016-03-21 at 09 57 27](https://cloud.githubusercontent.com/assets/704356/13913008/5cd280e2-ef4b-11e5-9ad2-d82df5ebb614.png)

**Comment by mcfedr** [comment]
I have made branches of both RestKit and AFNetworking that solve these problems

    pod 'RestKit', :git => 'https://github.com/mcfedr/RestKit.git', :branch => 'reachability'
    pod 'AFNetworking', :git => 'https://github.com/mcfedr/AFNetworking.git', :branch => 'reachability'

I have just removed the conditions for `#ifdef _SYSTEMCONFIGURATION_H` and everything works just fine.

**Comment by mcfedr** [comment]
Opened a pull request to AFNetworking for this https://github.com/AFNetworking/AFNetworking/pull/3400

**Comment by arismamo** [comment]
hi @mcfedr, i have installed your version and seems to work. Is your version going to be patched on the official release of Restkit 0.26.0? Thanks

**Comment by mcfedr** [comment]
Well AFNetworking have responded and said they won't do a patch release for 1.x
RestKit hasn't made any comment on my pull request.
So for the moment I am sticking to my branches.

**Comment by doncorsean** [comment]
From rest kit pod spec ln 19-24:  
# Add Core Data to the PCH if the Core Data subspec is imported. This enables conditional compilation to kick in.
  s.prefix_header_contents = <<-EOS
#if __has_include(<RestKit/CoreData.h>)
    #import <CoreData/CoreData.h>
#endif
EOS

I've always done like you suggested and commented the ifdefs out to make this work but wouldn't this work for sysconfig conditionals in AFNetworking?

# Add SystemConfiguration to the PCH if SystemConfiguration is imported. This enables conditional compilation to kick in.
  s.prefix_header_contents = <<-EOS
#if __has_include(<SystemConfiguration/SystemConfiguration.h>)
    #import <SystemConfiguration/SystemConfiguration.h>
#endif
EOS

**Comment by mcfedr** [comment]
I think the problems start because with use_frameworks there is no longer a single shared PCH file

**Comment by falkobuttler** [comment]
What is with the plans to upgrade RestKit to use AFNetworking 3.x? The first step to make it work using frameworks but the work doesn't really stop there...

**Comment by doncorsean** [comment]
Curious about the answer to @falkobuttler, The AFNetworking dependency has been in the 1.x for ages now....

**Comment by jkoehl** [comment]
@mcfedr I think this issue should be marked as "Open"

**Comment by mcfedr** [comment]
@jkoehl As far as I am concered its certainly not closed

**Comment by sarpsolakoglu** [comment]
None of the solutions seems to work for me. I'm using use_frameworks!, cocoapods 0.39.0, and RestKit 0.26.0. It's frustrating because I need to use a swift pod and cannot get rid of RestKit easily because it is a big project. @mcfedr your no_frameworks branch compiles but when I try to run the app it crashes inside RestKit, could I be doing something wrong?

**Comment by mcfedr** [comment]
@sarpsolakoglu Maybe you can give more details of the crash

**Comment by sarpsolakoglu** [comment]
@mcfedr It crashes on line 131 of RKRequestOperation.m with EXC_BAD_ACCESS. Maybe this is because of some other changes made on the development branch.
```
- (void)objectRequestOperationDidStart:(NSNotification *)notification
{
    RKObjectRequestOperation *objectRequestOperation = [notification object];
    
    //crashes here because objectRequestOperation is nil
    objc_setAssociatedObject(objectRequestOperation, RKOperationStartDate, [NSDate date], OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    
    NSURLRequest *request = objectRequestOperation.HTTPRequestOperation.request;
    RKLogInfo(@"%@ '%@'", request.HTTPMethod, request.URL.absoluteString);
    RKLogDebug(@"request.headers=%@", request.allHTTPHeaderFields);
    if (request.HTTPBody && RKLogIsTrace()) {
        RKLogTrace(@"request.body=%@", RKLogTruncateString([[NSString alloc] initWithData:request.HTTPBody encoding:NSUTF8StringEncoding]));
    }
}
```

**Comment by SCMcDonnell** [comment]
For what it's worth, @mcfedr's solution above worked great for me when it comes to this issue.  I was able to compile and all of my tests ran successfully.  Thank you.

**Comment by esusatyo** [comment]
@mcfedr's solution works – can we just merge it and cut a new release? A lot of people has been having this problem and it's been a problem for 6 months now.

**Comment by segiddins** [comment]
Sorry, I never saw that PR come in! It must've happened while I was on vacation

**Comment by falkobuttler** [comment]
CocoaPods 1.0 is out and it seems dev or master branch still don't support it.

**Comment by segiddins** [comment]
@falkobuttler no one has made a PR adding support yet

**Comment by erikackermann** [comment]
@segiddins can you give a summary of what still needs to be fixed for RestKit to compile with CocoaPods 1.0 and `use_frameworks!`?

Trying to figure out where to begin helping out with a patch, but there is so much outdated information in this issue thread that I'm not sure what still applies to 0.26.0 and CocoaPods 1.0 stable.

**Comment by segiddins** [comment]
@erikackermann ¯\_(ツ)_/¯ I don't know, I haven't actually used RestKit in > 2 years, I've just been doing my best to merge PRs

**Comment by thomaskoehn11** [comment]
fyi @segiddins @erikackermann: without `use_frameworks!` the workaround from @tengelmeier still worked for me yesterday (thanks btw!!!). workaround meaning:
```
post_install do |installer|
      installer.pods_project.targets.each do |target|
       if target.name == "Pods-Foo" or target.name == "Pods-Bar"
                puts "Updating #{target.name} HEADER_SEARCH_PATHS"
                target.build_configurations.each do |config|
                    xcconfig_path = config.base_configuration_reference.real_path
                xcconfig = File.read(xcconfig_path)
                    new_xcconfig = xcconfig.sub('HEADER_SEARCH_PATHS = $(inherited)', 'HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public/RestKit/CoreData" "${PODS_ROOT}/Headers/Public/RestKit/Network"  "${PODS_ROOT}/Headers/Public/RestKit/ObjectMapping" "${PODS_ROOT}/Headers/Public/RestKit/Support"')
                    File.open(xcconfig_path, "w") { |file| file << new_xcconfig }   
                end
            end
      end
    end
```

**Comment by mcfedr** [comment]
My fork, https://github.com/mcfedr/RestKit/tree/pods1 works with cocoapods v1.

    pod 'RestKit', :git => 'https://github.com/mcfedr/RestKit', :branch => 'pods1'

**Comment by erikackermann** [comment]
@mcfedr do you want to submit a PR from your `pods1` branch -> master on the main fork?  Is there any reason this isn't ready for release?

**Comment by erikackermann** [comment]
@mcfedr I am using your `pods` branch, and this AFNetworking dependency:

```
pod 'AFNetworking', :git => 'https://github.com/mcfedr/AFNetworking.git', :branch => 'reachability'
```

But I get `'RKValueTransformers/RKValueTransformers.h' file not found` on L21 in ObjectMapping.h.  Are you also explicitly including RKValueTransformers as a dependency?

**Comment by mcfedr** [comment]
@erichedstrom No its not in my pod file. I did have to clean everything, including the derived data after updating to cocoapods 1. otherwise I have the same setup as you.

**Comment by erikackermann** [comment]
@mcfedr I am not able to get this to compile with your branch (installing 0.26.0 release) and cocoapods 1.0.

**Comment by tstanik** [comment]
@erikackermann It works for me with RestKit `pods1` branch + AFNetworking `reachability` branch. Before that, with RestKit `reachability` branch I was getting `'RestKit/RKEntityMapping.h' file not found` error. Thank you @mcfedr 😉

**Comment by valeriomazzeo** [comment]
It seems to me that the RestKit development branch is ok, but there's an issue with `AFNetworking` `Reachability`. 

@mcfedr solution removes the defines from `AFNetworking` literally not constraining that enum anymore.

I have found out that
```
#if __IPHONE_OS_VERSION_MIN_REQUIRED
  #import <SystemConfiguration/SystemConfiguration.h>
  #import <MobileCoreServices/MobileCoreServices.h>
  #import <Security/Security.h>
#else
  #import <SystemConfiguration/SystemConfiguration.h>
  #import <CoreServices/CoreServices.h>
  #import <Security/Security.h>
#endif
```
it's correctly present in the `AFNetworking-prefix.pch` file as it should, but for some reason (using frameworks) the prefix file is ignored.
If we try add the above to the umbrella header `AFNetworking-umbrella.h`, it magically compiles.

Perhaps cocoapods when generating the umbrella header should include the content of the prefix file? @segiddins

**Comment by segiddins** [comment]
@valeriomazzeo the right solution is to move away from prefix headers entirely

**Comment by valeriomazzeo** [comment]
@segiddins what about existing pods compatibility? I think somehow we should ensure it's possible to install RestKit with Cocoapods 1.0

**Comment by mcfedr** [comment]
@valeriomazzeo My understand is how thats it because of how the frameworks are built as separate bundles of code, they dont see each others prefix headers so that kind of conditional compilation does work.

**Comment by valeriomazzeo** [comment]
@mcfedr I agree and that's how it should work. This code though:
```
#if __IPHONE_OS_VERSION_MIN_REQUIRED
  #import <SystemConfiguration/SystemConfiguration.h>
  #import <MobileCoreServices/MobileCoreServices.h>
  #import <Security/Security.h>
#else
  #import <SystemConfiguration/SystemConfiguration.h>
  #import <CoreServices/CoreServices.h>
  #import <Security/Security.h>
#endif
```

It's inside the AFNetworking prefix header generated by cocoapods, though, so in theory is part of AFNetworking not of RestKit.

**Comment by mcfedr** [comment]
@valeriomazzeo the prefix is used when it builds the framework AFNetworking, but its not visible when you import the headers from the built framework. The binary has the functions for Reachability, you can see them if you inspect the binary file.
But the header files in the `.framework` don't include the prefix, and your prefix isnt added to them. So the headers don't skip Reachability.
The errors/warnings are confusing because the same files are compiled in different contexts

**Comment by valeriomazzeo** [comment]
correct, that's why without modifying any file either for RestKit or AFNetworking, adding those in the umbrella header fixes it, but cocoapods doesn't do it.

**Comment by mcfedr** [comment]
Surely for us to change the umbrella file for AFNetworking that would also require a fork? Or does adding to RestKit fix the AFNetworking headers?

**Comment by valeriomazzeo** [comment]
I think the easier thing to do at the moment it would be to add a cocoapods post install script to the pod file that modifies the umbrella header when installing restkit.

This way we don't depend from external branches / fork and we have a full working installation hoping that we either remove the whole AFNetworking dependency one day, or cocoapods fix it somehow.

I have created an issue: https://github.com/CocoaPods/CocoaPods/issues/5390

**Comment by aqibmumtaz** [comment]
I use cocoapods 1.0.0 + ReskKit 0.26 + use_frameworks!

Dont work, When this issue will be fixed?

**Comment by Sajjon** [comment]
If anyone is having problems with RestKit 0.26.0 and Cocoapods 1.0.1, hopefully this will help!

This solution worked at least on 2016-06-03, but since it uses specific git branches maybe these will be merged, so if this does not work for you please check if this git branches have been merged/moved/deleted.

# Clean up before everything
Quit Xcode

    rm -rf Pods
    rm -rf MyApp.xcworkspace  
    rm -rf ~/Library/Caches/CocoaPods
    rm -rf ~/Library/Developer/Xcode/DerivedData

# Use [mcfedr's RestKit fork][1]
Must be used together with "reachablility" branch of AFNetworking

    pod 'AFNetworking', :git => 'https://github.com/mcfedr/AFNetworking.git', :branch => 'reachability'
    pod 'RestKit', :git => 'https://github.com/mcfedr/RestKit.git', :branch => 'pods1'

# Use module import syntax in Bridging Header

    @import RestKit;

Now it should work!


  [1]: https://github.com/mcfedr/RestKit/tree/pods1

**Comment by erikackermann** [comment]
@Sajjon thanks for putting all of this together in one comment.  Your steps worked for me.  Now let's get this merged into the main fork!

**Comment by jlampa** [comment]
What needs to happen for this to get this released?
I'm happy to do some work on it over the weekend if that helps.



-- 
Pozdrawiam,

JL

**Comment by valeriomazzeo** [comment]
Please read my post above. Not sure what's @segiddins' idea about this.

**Comment by doncorsean** [comment]
Why is this closed? Is this being tracked elsewhere? @Sajjon Seems to have a solution that can be absorbed and released to the public so we don't have to use a fork. I understand this may require coordination with AFNetworking team. Just curious as RestKit is used by so many and everyone has been dealing with this issue for some time now. Thank you all for you efforts to resolve. :)

**Comment by aqibmumtaz** [comment]
RESTKit is great framework, I use it mostly, I m desperately waiting for this issue to be fixed. How long will it take to merge fork into RESTKit ?

**Comment by valeriomazzeo** [comment]
has anyone tried what I mentioned? https://github.com/RestKit/RestKit/issues/2356#issuecomment-221093537

it's a very easy fix and it should work until we remove the AFNetworking dependency.

**Comment by kraftydevil** [comment]
@Sajjon can you elaborate on "Use module import syntax in Bridging Header"?

I'm not sure where this line should go:
`@import RestKit;`

**Comment by Sajjon** [comment]
@kraftydevil are you using Swift?

If you are, you have to import RestKit in you[ Bridging header,](http://stackoverflow.com/a/24005242/1311272) but usually this is done using:
```
#import <RestKit/RestKit....h>
```
You should use **@**import, notice "@"

**Comment by kraftydevil** [comment]
@Sajjon - Not using Swift so maybe that's what's throwing me off. I noticed talk of Bridging Headers when referencing Objective-C code, but I wasn't sure if Bridging Headers were unique to Swift.

Sounds like I can ignore it since my project isn't using Swift at all.

**Comment by Sajjon** [comment]
@kraftydevil yeah ignore that step then :) 

Is it working?

**Comment by kraftydevil** [comment]
I got a different, unrelated, error now so I'd say, yes :)

**Comment by erikackermann** [comment]
@Sajjon I had this in the .pch for my tests target:

```
#import <RestKit/Testing.h>
```

and `<RestKit/RestKit.h>` in my main target's precompile header.  What should I do to fix this import in my test target?

**Comment by Sajjon** [comment]
@erikackermann Is this a ObjC project? Have you tried changing to Module import syntax in the .pch file?

**Comment by Sajjon** [comment]
@kraftydevil what's the new error you got? did you manage to solve that? :)

**Comment by erikackermann** [comment]
@Sajjon yes, I switched to `@import RestKit;` in my main target's .pch.  But the testing target's .pch had `#import <RestKit/Testing.h>`.

I can't figure out a way to include the `Testing.h` header when importing RestKit as a module for my unit test target.  Additionally, when I do `@import RestKit;`, I get duplicate symbols error.

**Comment by kraftydevil** [comment]
@Sajjon - the error I eventually solved was unrelated to our topics but thanks for asking.

**Comment by Sajjon** [comment]
@erikackermann hmm tricky question, have you tried just:
```swift
@import Testing;
```
? 😬

**Comment by valeriomazzeo** [comment]
See https://github.com/RestKit/RestKit/pull/2434

**Comment by carlosriver24** [comment]
Hi @Sajjon 

I am fairly new to xcode and I am taking over an objective c project from a few developers. I am trying to follow your documentation, but when I run the github instructions I get "No such file or directory". I am originally getting the 'RKObjectMapping.h file not found'. What am I doing wrong?! Many thanks in advance.

**Comment by Sajjon** [comment]
@carlosriver24 are you using Xcode 7 or 8? Which pods version? I have only tested pods 1.0.1 and with Xcode 7.3 something.

**Comment by valeriomazzeo** [comment]
RestKit 0.27.0 is compatible with Cocoapods 1.0.1.
Please refer to #2434

**Comment by carlosriver24** [comment]
@Sajjon I am using Xcode 7.3, but not sure how to check the version of RestKit I have. Any thoughts?

**Comment by Sajjon** [comment]
Yes try 0.27 then hopefully everything will work out :)

**Comment by Sajjon** [comment]
Then you don't need my solution as valeriomazzeo wrote

**Comment by nezhyborets** [comment]
So can we !use_frameworks for RestKit now?

**Comment by valeriomazzeo** [comment]
@nezhyborets yes, please refer to #2434

**Comment by carlosriver24** [comment]
Thanks, all! I just needed to upgrade.
