### ISSUE TITLE
RKRequestDescriptor & RKResponseDescriptor method is ambiguous

### ISSUE THREAD

**Issue by vyacheslavk** [RestKit/RestKit#2365]
Can't set POST method for descriptors 
 
`Reference to 'RKRequestMethodPOST' is ambiguous`

example code 
    `RKObjectMapping *requestMapping = [Register actionRequestMapping];
    RKRequestDescriptor *requestDescriptor = [RKRequestDescriptor requestDescriptorWithMapping:requestMapping
                                                                                   objectClass:RegisterRequest.class
                                                                                   rootKeyPath:nil
                                                                                        method:RKRequestMethodPOST];`

using Xcode 7.1.1 (7B1005) & Restkit 0.25.0

**Comment by segiddins** [comment]
That's really odd... It works fine in the RestKit tests. Have you tried with 0.26?

**Comment by vyacheslavk** [comment]
Yes, I tried 0.26 but i had an issue with `use_frameworks!`  in my project
