### ISSUE TITLE
Unable to satisfy the following requirements:  - `RestKit (~> 0.24.0)` required by `Podfile`

### ISSUE THREAD

**Issue by NelepovDmitry** [RestKit/RestKit#2379]
Use docs create a podfile with source

platform :ios, '5.0'

pod 'RestKit', '~> 0.24.0’

and then run 
pod install

i got error
[!] Unable to satisfy the following requirements:

- `RestKit (~> 0.24.0)` required by `Podfile`

**Comment by segiddins** [comment]
Restkit does not support 5 any more

**Comment by NelepovDmitry** [comment]
Yes, thank you this pod file works fine:
platform :ios, ‘8.0’

pod 'RestKit', '~> 0.24.0’

Will u update readme at https://github.com/RestKit/RestKit ?
