### ISSUE TITLE
RestKit does not compile on cocoapods 1.0.0

### ISSUE THREAD

**Issue by JoeShi** [RestKit/RestKit#2393]
If upgrade the cocoapods to 1.0.0. The ReskKit stops compiling.

**Comment by tengelmeier** [comment]
See issue #2356

**Comment by valeriomazzeo** [comment]
See https://github.com/RestKit/RestKit/pull/2434

**Comment by JoeShi** [comment]
Hello, @valeriomazzeo  Thank you very much for fixing the error. Could you please make a release and update the pod file.. 

The latest release is on 2015..

**Comment by valeriomazzeo** [comment]
Will di once the pull request is ready, there is still an issue to solve, related to the project configuration
