### ISSUE TITLE
Changelogs? Version history?

### ISSUE THREAD

**Issue by max-pfeiffer** [RestKit/RestKit#2411]
Since V0.24.1 I cannot find information in the [changelog](https://github.com/RestKit/RestKit/releases) or version history.

I saw that sice then V0.25.0 and V0.26.0 have been released. It would be very nice if the changes could be published there briefly.

That would make upate decisions easier. Right know I have to dig through the commits to see what has happend.

**Comment by segiddins** [comment]
If someone writes up changelogs, I'll be happy to add them to the releases.
