### ISSUE TITLE
CocoaLumberjack in podspec

### ISSUE THREAD

**Issue by shvekiasaf** [RestKit/RestKit#2416]
Hey

Can you please a support for Cocoalumberjack to the podspec version 0.25.
I'm having Cocoalumberjack in my project and there is no way to link the RestKit library with the Cocoalumberjack library.

This is the error I get:
> Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DDLog", referenced from:
      objc-class-ref in RKLumberjackLogger.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I saw this line in the podspec of 0.26 and it seems exactly like what I need.

{
      "name": "CocoaLumberjack",
      "source_files": "Code/CocoaLumberjack/RKLumberjackLogger.*",
      "dependencies": {
        "CocoaLumberjack": [

        ],
        "RestKit/Support": [

        ]
      }
    }

Thanks.

**Comment by segiddins** [comment]
Its in the 0.26 podspec, just use 0.26 if its something you need.

**Comment by shvekiasaf** [comment]
I want to but on version 0.26, I get the file not found error.

Pods/RestKit/Code/CoreData.h:22:9: 'RestKit/CoreData/RKEntityMapping.h' file not found

#2356 

Had you guys already solved the issue?

**Comment by segiddins** [comment]
Unsure, you'll have to read through the issues

**Comment by mcfedr** [comment]
@shvekiasaf this has been fixed by https://github.com/RestKit/RestKit/pull/2404 should be released as 0.26.1 soon

**Comment by shvekiasaf** [comment]
@mcfedr Sounds awesome! Thanks a lot!

**Comment by shvekiasaf** [comment]
Hey @segiddins do you have an estimation, even a rough one, when will the new version be released? Thanks man!
