### ISSUE TITLE
link_with in the Podfile is now unsupported, please use target blocks instead

### ISSUE THREAD

**Issue by TaoistKing** [RestKit/RestKit#2421]
**When I execute pod install:**

[!] Invalid `Podfile` file: [!] The specification of `link_with` in the Podfile is now unsupported, please use target blocks instead..
 #  from /Users/Ray/demos/RestKit/Podfile:31
 #  -------------------------------------------
 #    platform :ios, '5.1.1'
 >    link_with 'RestKitTests'
 #    import_pods
 #  -------------------------------------------

**then I change 'link_with' with 'target', still get error:**

[!] Unable to find a target named `ios`, did find `RestKit`, `RestKitTests`, `RestKitFramework`, and `RestKitFrameworkTests`.

**what should I do?**

**Comment by segiddins** [comment]
RestKit still requires CocoaPods 0.39, please use the Gemfile.

**Comment by TaoistKing** [comment]
any instructions to follow? not familiar with Gemfile

**Comment by btechlabs** [comment]
Having similar issue... Trying to build a gba4ios xcode project for testing on my phone and am getting the same error. SOS

**Comment by valeriomazzeo** [comment]
The latest version of RestKit is compatible with Cocoapods 1.3.1, so you need to use the latest cocoapods syntax in the podfile.
