### ISSUE TITLE
Release notes are missing for 0.25 and 0.26

### ISSUE THREAD

**Issue by mplorentz** [RestKit/RestKit#2426]
There aren't any release notes for versions 0.25 and 0.26. Apparently there were breaking changes to the API in this update, but I can't find any information on what they were or what the upgrade path is.

**Comment by segiddins** [comment]
Feel free to write release notes.

**Comment by mplorentz** [comment]
@segiddins why such a dismissive tone? Can you explain the reasoning behind releasing without a changelog? It seems reasonable to expect a mature project like RestKit to document its changes.

**Comment by segiddins** [comment]
Because the choice was no release or a release without a CHANGELOG and let someone contribute one after the fact. There have been other issues opened on the subject.
