### ISSUE TITLE
RestKit and IPV6

### ISSUE THREAD

**Issue by Sagarhebbale** [RestKit/RestKit#2435]
I am using Restkit 0.24.0 for my iOS application and i wanted to check if it supports IPV6 only networks or just IPV4? Apple from this June are forcing all apps to work on IPV6 only networks and i was wondering if RESTKit 0.24.0 supports this. If not, should i update my RESTKit version? Or what work arounds do i have so that i can submit the application using RESTKit?

**Comment by segiddins** [comment]
RestKit just uses aftnetworking 1.0 under the hood, which means the deprecated NSURLConnection suite of classes.

**Comment by Sagarhebbale** [comment]
Ok. Is there a version of RESTKit that supports IPV6? 

Otherwise i will have to re write some of the RESTful interactions using NSURLSession instead. While this is possible, its not a version of RESTKit that supports this would save me some time!

**Comment by segiddins** [comment]
Some people have been working on rewriting the networking internals of RK, have a poke around the open issues and you'll find them.
