### ISSUE TITLE
RestKit objectMapper pathpattern reserved word “categories”?

### ISSUE THREAD

**Issue by alexagat** [RestKit/RestKit#2436]
I am writing a RESTful API, and consuming that API in an iOS application, using RestKit to map JSON to `NSManagedObject`s. The project is working, and consuming 2 entity types already.

I am now writing some routes/RestKit logic around an object I call "Category"

When I add a responseDescriptor to the RKObjectManager with a pathPattern of "categories" and run an API call using the RKObjectManager's getObjectsAtPath with a path of "categories", and thusly change my API route URI be named "categories", RestKit throws a 401, even though I see I am sending the correct authorization header, as well as I can hit the endpoint through PostMan / a similar tool and get back a 200.

Yet, if I change these three properties (the API route URI, the RKObjectManager responseDescriptor's pathPattern, and the RKObjectManager getObjectsAtPath function's path to "category" or "foo" or "asdf", it works.

Not working:

    objectManager.addResponseDescriptor(
        RKResponseDescriptor(
            mapping: categoryMapping,
            method: RKRequestMethod.GET,
            pathPattern: "/categories",
            keyPath: "results",
            statusCodes: RKStatusCodeIndexSetForClass(RKStatusCodeClass.Successful)
        )
    )

    RKObjectManager.sharedManager().getObjectsAtPath(
        "/categories",
        parameters: nil,
        success: { (operation: RKObjectRequestOperation!, result: RKMappingResult!) -> Void in
                
            let categories = result.array() as! [Category] 
            completion?(categories: categories)
        },
        failure: { (operation: RKObjectRequestOperation!, error: NSError!) -> Void in
            print("!!Mapping Error!!")
            failure?(error: error)
        }
    )

I get a 401 request, even though I print out that I am sending the correct 'authorization' header (as I am also doing in my other API requests to get various objects back from the API):

`restkit.network:RKObjectRequestOperation.m:137 GET 'http://a3d6668d.ngrok.io/categories'
2016-06-28 20:41:15.655 DateNight[4271:4295563] E restkit.network:RKObjectRequestOperation.m:510 Object request failed: Underlying HTTP request operation failed with error: Error Domain=org.restkit.RestKit.ErrorDomain Code=-1011 "Expected status code in (200-299), got 401" UserInfo={NSLocalizedRecoverySuggestion={"error":"Unauthenticated: Unauthenticated"}`

HOWEVER, when no other code changes but the name of the path (from "categories" to "category" or "foo") things work perfectly.

Working:

    objectManager.addResponseDescriptor(
        RKResponseDescriptor(
            mapping: categoryMapping,
            method: RKRequestMethod.GET,
            pathPattern: "/category",
            keyPath: "results",
            statusCodes: RKStatusCodeIndexSetForClass(RKStatusCodeClass.Successful)
        )
    )

    RKObjectManager.sharedManager().getObjectsAtPath(
        "/category",
        parameters: nil,
        success: { (operation: RKObjectRequestOperation!, result: RKMappingResult!) -> Void in
                
            let categories = result.array() as! [Category]
            completion?(categories: categories)
        },
        failure: { (operation: RKObjectRequestOperation!, error: NSError!) -> Void in
            print("!!Mapping Error!!")
            failure?(error: error)
        }
    )

Response: `GET 'http://a3d6668d.ngrok.io/category' (200 OK / 3 objects) [request=0.8262s mapping=0.0072s total=0.8359s]`

Any idea what could be going on here?

**Comment by valeriomazzeo** [comment]
As far as I know, there's no such thing like a reserved keyword for categories. I have been using it myself in the past without any issue.

My recommendation is to enable logging for the network module and print out the request that get sent so you can compare it with what you send through postman.

**Comment by alexagat** [comment]
Sorry, this ended up being a mistake completely on my end. Closing.
