### ISSUE TITLE
rejected by appstore

### ISSUE THREAD

**Issue by wweennbboo** [RestKit/RestKit#2460]
Our project using RestKit(0.20.3) is rejected by appstore recently, it's no problem before, we need your kindly help, pls refer below of apple's reply, thanks... ('mainQueueManagedObjectContext' is the property of 'RKManagedObjectStore')

![default](https://cloud.githubusercontent.com/assets/8406701/18859515/a79dc654-8429-11e6-97bb-ffbab246483c.png)

**Comment by valeriomazzeo** [comment]
I am not sure whether in `0.20.3` `RestKit` was using a private API or not. It's definitely unlucky to be true, but you can double check. If that's the case, simply upgrading to the latest version of RestKit should fix your issue.

There is a property with that name in the current version, but it's definitely not a private API (it's defined in one of `RestKit`'s classes) and it hasn't caused any issue with Apple's reviews so far.

**Comment by wweennbboo** [comment]
@valeriomazzeo  we have already renamed the property ‘mainQueueManagedObjectContext’, and it finally succeed to submit to app store by getting through appstore review, thanks.

**Comment by valeriomazzeo** [comment]
👍
