### ISSUE TITLE
RKObjectMapping.h file not found(RestKit version 0.26.0)

### ISSUE THREAD

**Issue by fifyrio** [RestKit/RestKit#2495]
I set the pod file as this:
```
target 'tableView' do    
    pod 'RestKit'
end
```
,then I run ' pod install --no-repo-update'
and RKObjectMapping.h file not found, even though it exists

**Comment by robertturrall** [comment]
I have the same problem with Restkit 0.24.0 - I used this version as your readme explicitly shows it as the version to use with CocoaPods. 

Is this going to be resolved? Is there a way around this?

I've decided to use Restkit in a client app but cannot afford to wait months for even a clean compile. Please post an update. If necessary I'll drop Restkit, which will give me more work. I, and others, need to know though.

Thanks!

**Comment by valeriomazzeo** [comment]
Last version of restkit is 0.27.2 and that's what you should be installing.
