### ISSUE TITLE
Support with other swift Cocoapods

### ISSUE THREAD

**Issue by kpavankotesh** [RestKit/RestKit#2498]
Hey, 

When I use use_frameworks! to support other swift pods along with RestKit it gives issues. Is there any way to avoid this along with using RestKit?

**Comment by loudmouth** [comment]
@kpavankotesh there are two things to do when using RestKit with the `use_frameworks!` flag in your Podfile

1. Import RestKit as a module:

```
@import RestKit; // yes
#import <RestKit/RestKit.h> // no
```

2. It's possible you'll need to delete the cached pod. Remove the following directories from you machine:

```
rm -rf ~/Library/Caches/Cocoapods
rm -rf ~/Library/Developer/Xcode/DerivedData/
```

**Comment by kpavankotesh** [comment]
It works along with use_frameworks! and bridging header. Thanks
