### ISSUE TITLE
Impossible to not save to persistent store

### ISSUE THREAD

**Issue by YBthebest** [RestKit/RestKit#2511]
Hi. I just fully integrated RestKit into my iOS app but I'm running into this issue since a couple of days and it's driving me nuts.

I'm incapable of fetching and mapping objects to CoreData without automatically persisting them on disk. I want to be able to use CoreData as an in-memory store, and optionally persist the data if the user wants to download it.

I was always using `getObjectsAtPath` but I coded a separate `RKManagedObjectRequestOperation` specifically so that I could set `operation.savesToPersistentStore = FALSE;`, but even then, the data gets persisted anyhow to the MainQueue. Am I misunderstanding/misusing something, or is this an issue?

Thanks a lot

**Comment by valeriomazzeo** [comment]
Hi @YBthebest,

It seems to me, that it works as intended.

From the documentation:
```
/**
 A Boolean value that determines if the operation saves the mapping results to the persistent store upon successful completion. If the network transport or mapping portions of the operation fail the operation then this option has no effect.
 
 When `YES`, the receiver will invoke `saveToPersistentStore:` on its private managed object context to persist the mapping results all the way back to the persistent store coordinator. If `NO`, the private mapping context will be saved causing the mapped objects to be 'pushed' to the parent context as represented by the `managedObjectContext` property.
*/

@property (nonatomic, assign) BOOL savesToPersistentStore;
```

`savesToPersistentStore` will still save data to its private context first and its parent context after.

When using `getObjectsAtPath`, the parent context is `mainQueueManagedObjectContext` (`RKObjectManager.m` line 661) :

```
NSManagedObjectContext *managedObjectContext = [object respondsToSelector:@selector(managedObjectContext)] ? [object managedObjectContext] : self.managedObjectStore.mainQueueManagedObjectContext;
```

It's very likely for `mainQueueManagedObjectContext` to be saved at some point, and because it is a child of `persistentStoreManagedObjectContext`, data will be written to disk.

I suggest, you make sure that your `ManagedObjectOperation` doesn't have a context which relates to `mainQueueManagedObjectContext`, or to create two separate CoreData stacks (use two different `ObjectManager`), with two different configurations.

**Comment by YBthebest** [comment]
Hi @valeriomazzeo, first of all thank you so much for taking the time to answer as I'm really becoming a bit desperate.

You're completely right: it is the intended behaviour. I've been doing some more research and it does work exactly as it should.

I'm still lost regarding this simple question: is it possible to use RestKit with CoreData without necessarily persisting all the data? How can I use CoreData just as a temporary database, while persisting when I need to?

I suppose I indeed have to use two different ObjectManagers, but I'm a bit lost as to how I should solidly implement this on initializiation.
Right now my launch looks like this:

`RKObjectManager *objectManager = [RKObjectManager managerWithBaseURL:[NSURL URLWithString:@"URL"]];
    objectManager.requestSerializationMIMEType = RKMIMETypeJSON;
    
    [RKObjectManager setSharedManager:objectManager];
    
    NSURL *modelURL = [[NSBundle mainBundle] URLForResource:@"XXXDataModel" withExtension:@"momd"];
    NSManagedObjectModel *managedObjectModel = [[NSManagedObjectModel alloc] initWithContentsOfURL:modelURL];
    // Initialize managed object store
    RKManagedObjectStore *managedObjectStore = [[RKManagedObjectStore alloc] initWithManagedObjectModel:managedObjectModel];
    objectManager.managedObjectStore = managedObjectStore;
    [managedObjectStore createPersistentStoreCoordinator];
    
    NSString *storePath = [RKApplicationDataDirectory() stringByAppendingPathComponent:@"XXXDB.sqlite"];
    NSString *seedPath = [[NSBundle mainBundle] pathForResource:@"RKSeededDB" ofType:@"sqlite"];
    NSError *error;
    NSPersistentStore *persistentStore = [managedObjectStore addSQLitePersistentStoreAtPath:storePath fromSeedDatabaseAtPath:seedPath withConfiguration:nil options:nil error:&error];
    NSAssert(persistentStore, @"Failed to add persistent store with error: %@", error);
    
    // Create the managed object contexts
    [managedObjectStore createManagedObjectContexts];
    
    // Configure a managed object cache to ensure we do not create duplicate objects
    managedObjectStore.managedObjectCache = [[RKInMemoryManagedObjectCache alloc] initWithManagedObjectContext:managedObjectStore.persistentStoreManagedObjectContext];`

and after this I add my ResponseDescriptors, like this:
`RKResponseDescriptor *establishmentsResponseDescriptor =
    [RKResponseDescriptor responseDescriptorWithMapping:[Establishment entityMappingForManagedObjectStore:managedObjectStore]
                                                 method:RKRequestMethodGET
                                            pathPattern:@""
                                                keyPath:nil
                                            statusCodes:[NSIndexSet indexSetWithIndex:200]];
    [objectManager addResponseDescriptor:establishmentsResponseDescriptor];`

Now I just have to have a better understanding of CoreData's functioning to figure out the best way to handle two different contexts (because when I will have persisted the data, I will want to retrieve data from a certain context if it is persisted, and otherwise check if it is in my regular in-memory context, and if neither, fetch and drop it into my in-memory context, basically).

Anyways, all help would be greatly appreciated, thanks a bunch!

**Comment by valeriomazzeo** [comment]
Although, in theory you don't really need two managers. if you go down that road (two `ObjectManager`) you will also need two `ManagedObjectStore`.

Each `ManagedObjectStore` deals with one and only one, `PersistentStoreCoordinator`, you are just using a convenience method: `addSQLitePersistentStoreAtPath` that creates a Core Data Stack backed by a SQLite for you. 

No one stops you to use directly `initWithPersistentStoreCoordinator:` to be able to back the `ManagedObjectStore` with an `InMemory` Core Data Stack instead.

I suppose you could load the same model into two different persistent stores, but then you will need to have something in between that handles the replication. It looks a bit overkill for what you have to do.

Have you considered using just `RKManagedObjectOperation` without the `ObjectManager`? That way you have full control on which `ManagedObjectContext` a `RKManagedObjectOperation` will use. 

If you'd still like to take advantage of the routing, that the `ObjectManager` provides, be aware that you can use some helpers methods such as:

- `requestWithObject`
- `managedObjectRequestOperationWithRequest`

To create your own `RKManagedObjectRequestOperation`, once you have that, you can easily change the `managedObjectContext` property to what you desire.

Or, you could subclass `ObjectManager` to provide an helper method that is equivalent to `getObjectsAtPath` but that returns you a `RKManagedObjectRequestOperation` that you can manipulate.

I'd recommend for simplicity to avoid having two core data stacks, as it looks to me that for your simple scenario, all you have to do is to orchestrate the context the way you prefer.

Either way, I'd recommend to whoever uses `RestKit` to have a good understanding of how `Core Data` works.

**Comment by YBthebest** [comment]
I honestly can't thank you enough. You've just managed to push me over the edge of comprehension far enough that it all suddenly made sense. I'm using my two contexts now, and it's working smoothly. Thank you so, so, so much.

**Comment by valeriomazzeo** [comment]
Glad to be helpful 👍 

I should dig more into the implementation details to be able to answer your question correctly, but I suppose you can't really get advantage of the cache if you are not saving the objects.

In fact, one of the purposes of the cache is to avoid duplicated objects, and there's no way to achieve that if you are not saving them back to the persistent store.

If you look at `RKObjectManager.m line: 623`:

```
operation.managedObjectCache = self.managedObjectStore.managedObjectCache;
```

You can see that calling that method from `[RKObjectManager sharedManager]` , applies the same cache that is defined on the `ManagedObjectStore` attached to the `ObjectManager`.

I suppose, in your case, you can set that to `nil` for your `RKManagedObjectRequestOperation` as you don't really get any advantage from that without saving the objects, and that should also get rid of the error.

If you'd like to know more about the `managedObjectCache` you can find some documentation here:

>The managed object cache associated with the managed object request operation.
>
 >The cache is used to look up existing objects by primary key to prevent the creation of duplicate objects during mapping. Please see the above discussion of 'Managed Object Caching' for more details.
>
>@warning A `nil` value for the `managedObjectCache` property is valid, but may result in the creation of duplicate objects.

And a detailed discussion at line 45 of the same file (`RKManagedObjectRequestOperation.h`):

>## Identification Attributes &amp; Managed Object Caching
>
>When object mapping managed objects it is necessary to differentiate between objects that already exist in the local store and those that are being created as part of the mapping process. This ensures that the local store does not become populated with duplicate records. To make this differentiation, RestKit requires that each `RKEntityMapping` be configured with one or more identification attributes. Each identification attribute must correspond to a static attribute assigned by the remote backend system. During mapping, these attributes are used to search the managed object context for an existing managed object. If one is found, the object is updated else a new object is created. Identification attributes are configured on the `[RKEntityMapping identificationAttributes]` property.
>
>Identification attributes are used in conjunction with the `RKManagedObjectCaching` protocol. Each managed object request operation is associated with an object conforming to the `RKManagedObjectCaching` protocol via the `managedObjectCache` proeprty. This cache is consulted during mapping to find existing objects and when establishing relationships between entities by one or more attributes. Please see the documentation accompanying `RKManagedObjectCaching` and `RKConnectionDescription` classes for more information.

Ps: perhaps mapping is slow because is trying to log a lot of errors in the console, you can verify this disable the logging.
