### ISSUE TITLE
App crashes when calling "refreshAllObjects" in iOS 8

### ISSUE THREAD

**Issue by bharath-dev** [RestKit/RestKit#2543]
I have used "refreshAllObjects" method and it always crashes in iOS 8(I have tested in 8.1.3) but it works fine in iOS 11 & iOS 12 versions
![screenshot 2018-10-05 at 6 12 31 pm](https://user-images.githubusercontent.com/16458195/46535951-98f5e180-c8ca-11e8-9b2d-a1465ea8a229.png)

**Comment by bafnaparag** [comment]
`- (void)refreshAllObjects API_AVAILABLE(macosx(10.11),ios(8.3));`

Its available from iOS 8.3
