### ISSUE TITLE
.NET Date Formatting

### ISSUE THREAD

**Issue by blakewatters** [RestKit/RestKit#264]
This is an issue that has come up a number of times. Given that we are moving to iOS 4.0+ as the deployment target, we should be able to use regular expressions to handle this more easily at the framework level.

http://groups.google.com/group/restkit/browse_frm/thread/8c8e6551d01fbf5d/cf5fb07a65702c64?lnk=gst&q=.net#cf5fb07a65702c64

**Comment by exalted** [comment]
For future reference: above link is dead, instead please go to https://gist.github.com/exalted/726910
