### ISSUE TITLE
Object's persistent store is not reachable from this NSManagedObjectContext's coordinator 

### ISSUE THREAD

**Issue by francescopetrungaro** [RestKit/RestKit#397]
Hello, 
I have the following error using my app: 

'Object's persistent store is not reachable from this NSManagedObjectContext's coordinator' 

Now, my app has RestKit and standard coreData configuration to be able to store other information. it works really well but sometimes I receive that crash. Do you know why? 

I have the last version of Restkit with the fix: 
// Clear the current managed object context. Will be re-created next time it is accessed. 
NSMutableDictionary\* threadDictionary = [[NSThread currentThread] threadDictionary]; 
if ([threadDictionary objectForKey:kRKManagedObjectContextKey]) { 
[threadDictionary removeObjectForKey:kRKManagedObjectContextKey]; 
} 

but I think that error is still there. 
Any ideas? 

Thanks!!

**Comment by TechbirdsYogendra** [comment]
I'm having the same issue when using fetchedResultController.fetchedObjects.
