### ISSUE TITLE
Can I use DynamicObjectMapping with Serialization phase?

### ISSUE THREAD

**Issue by wangpingsx** [RestKit/RestKit#907]
i solve the boy/gril problem by DynamicObjectMapping.

but my problem is more than boy/gril issue. in my situation, the boy class has a attribute which is "girlfriend", and the gril class has "boyfriend" attribute. 

so when i load all data from json,  DynamicObjectMapping is just great.

but when i try to send a gril object or boy object to back-end, i can not use DynamicObjectMapping, yes i can use :
[[RKObjectManager sharedManager]  postObject:ren mapResponseWith:[self getRest2VOMapping] delegate:self];
but i need specific the mapping object each time, which is so annoyed.

please let me know what is the appropriate way to do the boy/gril issue for  the Serialization phase?
thanks by any help!
thank you!

**Comment by emmceemoore** [comment]
Still an issue for me as well using RestKit 0.24.1. I think this should be re-opened.
