### ISSUE TITLE
Serializer should have hooks so we can render BOOLs as proper JSON true/false

### ISSUE THREAD

**Issue by zorn** [RestKit/RestKit#920]
I'm using the serialization stuff to POST and PUT things. I have BOOLs I need to send up the wire as proper JSON `true` and `false` values. I found my stuff was always being encoded as NSNumbers since that's how they are stored.

I'd like a way to when defining the serialization mapping to hint that I want these JSON bool values.

I've hacked this into the my own branch with this commit. It's based off of Master cause that's what I'm using. Feel free to use it.

https://github.com/zorn/RestKit/commit/2df61925d7f0746071267e7e1b8e04feb8dd78c5

**Comment by elviin** [comment]
When the url parameters are used the serialization does not work. I had to register a subclassed class from RKURLEncodedSerialization. And this solution does not work for GET, HEAD and DELETE.

e.g. this way:

`static NSString * TSNRKAFQueryStringFromParametersWithEncoding(NSDictionary *parameters, NSStringEncoding stringEncoding) {

    NSMutableArray *mutablePairs = [NSMutableArray array];

    for (TSNRKAFQueryStringPair *pair in TSNRKAFQueryStringPairsFromDictionary(parameters)) {
        
        if([NSStringFromClass([pair.value class]) isEqualToString:@"__NSCFBoolean"]) {
            
            pair.value = TSNNSCFBooleanToBooleanStringConvertor(pair.value);
        }
        
        [mutablePairs addObject:[pair URLEncodedStringValueWithEncoding:stringEncoding]];
    }
    
    return [mutablePairs componentsJoinedByString:@"&"];
}`

For GET, HEAD and DELETE it would be nice to also have an option to register a serialization class.
