### ISSUE TITLE
Missing testing files on development

### ISSUE THREAD

**Issue by ErikEvenson** [RestKit/RestKit#988]
RestKit/Core/Testing.h tries to import RKTestFixture.h which is not available in the project.

**Comment by GabLeRoux** [comment]
In case someone was looking for this like I did, [here's how you install a subspec](http://stackoverflow.com/questions/20345566/how-do-you-install-a-pods-sub-spec-without-installing-the-whole-pod)

In your `podfile`:

```
def testing_pods
  ...
  pod 'RestKit/Testing', '~> 0.27.0'
end

target 'Your App Tests' do
  some_other_pods
  testing_pods
end
```
